<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0" targetNamespace="urn:LinqToXsdCore:Xml.Schema.Linq.CodeGen"
    xmlns="urn:LinqToXsdCore:Xml.Schema.Linq.CodeGen">
    <xs:element name="Graph">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="Schema"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Schema">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Includes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="Schema"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Imports">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="Schema"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="Name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>
