<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="orm-ml.xsd" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="orm-ml.xsd" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\XObjectsCore\XObjectsCore.csproj">
      <SetTargetFramework>TargetFramework=netstandard2.0</SetTargetFramework>
    </ProjectReference>
  </ItemGroup>
</Project>