<?xml version="1.0" encoding="utf-8" ?>
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  -->
<!-- Schema: Query.Office.Context.xsd                           -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="urn:Microsoft.Search.Query.Office.Context"
            xmlns="urn:Microsoft.Search.Query.Office.Context"
            elementFormDefault="qualified"
            xmlns:t="urn:Microsoft.Search.Types">
	<xsd:annotation>
		<xsd:documentation>
			This document is provided for informational purposes
			only. MICROSOFT MAKES NO WARRANTIES, EXPRESS OR IMPLIED,
			AS TO THE INFORMATION IN THIS DOCUMENT. Complying with
			all applicable copyright laws is the responsibility of
			the user.  Microsoft may have patents, patent
			applications, trademarks, copyrights, or other
			intellectual property rights covering subject matter in
			this document. Except as expressly provided in any
			written license agreement from Microsoft, the furnishing
			of this document does not give you any license to these
			patents, trademarks, copyrights, or other intellectual
			property. (c) 2003 Microsoft Corporation. All rights
			reserved.
		</xsd:documentation>
		<xsd:documentation>
			Defines context information augmenting a query.  The root
			element in this schema is designed to be used inside the
			Microsoft.Search.Query.xsd schema.
		</xsd:documentation>
	</xsd:annotation>
	<xsd:import schemaLocation="Microsoft.Search.Types.xsd"
	            namespace="urn:Microsoft.Search.Types" />
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Root Element: OfficeContext                       -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:element name="OfficeContext">
		<xsd:annotation>
			<xsd:documentation>
				Context information that may be useful in better
				handling the query.  Describes context information
				generated by Microsoft Office.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="UserPreferences"
				             type="UserPreferencesType" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>
							User information and preferences.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="ServiceData"
				             type="ServiceDataType" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>
							Data that the service has
							stored with Office.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="ApplicationContext"
				             type="ApplicationType" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>
							The name and version of the
							application the user is in.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="QueryLanguage" type="xsd:language"
				             minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>
							Language the query is in,
							if the application knows it.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="KeyboardLanguage"
				             type="xsd:language" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>
							Language corresponding to the keyboard.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:any namespace="##other" minOccurs="0"
				         maxOccurs="unbounded" processContents="skip">
					<xsd:annotation>
						<xsd:documentation>
							Any element in another namespace. Can
							be used for extensibility in the future.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:any>
			</xsd:sequence>
			<xsd:attribute name="revision"
			               type="xsd:unsignedInt" use="optional">
				<xsd:annotation>
					<xsd:documentation>
						Unsigned integer indicating the
						revision of the schema used in the request.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="build" type="t:String255"
			               use="optional">
				<xsd:annotation>
					<xsd:documentation>
						The build of the component used
						to generate the request.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Type: UserPreferencesType                         -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:complexType name="UserPreferencesType">
		<xsd:annotation>
			<xsd:documentation>
				Describes user information and preferences.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="ParentalControl"
			             type="xsd:boolean" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						Set to true if the user
						requests filtered content.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:any namespace="##other" minOccurs="0"
			         maxOccurs="unbounded" processContents="skip">
				<xsd:annotation>
					<xsd:documentation>
						Any element in another namespace. Can be
						used for extensibility in the future.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:any>
		</xsd:sequence>
	</xsd:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Type: ServiceDataType                             -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:complexType name="ServiceDataType">
		<xsd:annotation>
			<xsd:documentation>
				Describes service-specific data stored with Office.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Data" type="t:String255"
			             minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Data.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:any namespace="##other" minOccurs="0"
			         maxOccurs="unbounded" processContents="skip">
				<xsd:annotation>
					<xsd:documentation>
						Any element in another namespace.
						Can be used for extensibility in the future.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:any>
		</xsd:sequence>
	</xsd:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Type: ApplicationType                             -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:complexType name="ApplicationType">
		<xsd:annotation>
			<xsd:documentation>
				Describes data about the application the user is in.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Name" type="t:String255"
			             minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						Application Name.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Version" type="t:String255"
			             minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						Application Version.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="SystemInformation"
			             type="SystemInformationType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						Information about the system that is sending
						the query.  The service provider can use
						this to determine how to respond.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:any namespace="##other" minOccurs="0"
			         maxOccurs="unbounded" processContents="skip">
				<xsd:annotation>
					<xsd:documentation>
						Any element in another namespace.  Can be
						used for extensibility in the future.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:any>
		</xsd:sequence>
	</xsd:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Type: SystemInformationType                       -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:complexType name="SystemInformationType">
		<xsd:annotation>
			<xsd:documentation>
				Describes information about the system that is
				requesting the information.  The service provider
				can use this to determine how to respond.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="SkuLanguage" type="xsd:language"
			             minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						The system's main language.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="LanguagePack" type="xsd:language"
			             minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>
						One of the system's language flavors.
						There could be multiple ones.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="InterfaceLanguage" type="xsd:language"
			             minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						The current language of the user interface.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Location" type="t:ISO3166Type"
			             minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						Country or region indicating the current
						location of the system.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:any namespace="##other" minOccurs="0"
			         maxOccurs="unbounded" processContents="skip">
				<xsd:annotation>
					<xsd:documentation>
						Any element in another namespace.  Can be
						used for extensibility in the future.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:any>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>