<?xml version="1.0" encoding="utf-8" ?>
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!-- Schema: Response.Form.xsd                                   -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="urn:Microsoft.Search.Response.Form"
            xmlns="urn:Microsoft.Search.Response.Form"
            elementFormDefault="qualified"
            xmlns:t="urn:Microsoft.Search.Types">
	<xsd:annotation>
		<xsd:documentation>
			This document is provided for informational purposes
			only. MICROSOFT MAKES NO WARRANTIES, EXPRESS OR IMPLIED,
			AS TO THE INFORMATION IN THIS DOCUMENT. Complying with
			all applicable copyright laws is the responsibility of
			the user.  Microsoft may have patents, patent
			applications, trademarks, copyrights, or other
			intellectual property rights covering subject matter in
			this document. Except as expressly provided in any
			written license agreement from Microsoft, the furnishing
			of this document does not give you any license to these
			patents, trademarks, copyrights, or other intellectual
			property. (c) 2003 Microsoft Corporation. All rights
			reserved.
		</xsd:documentation>
		<xsd:documentation>
			Forms enable a service to interact with the user.
			Defines all form elements and their relationship to each
			other.  A form is submitted when the user clicks a form
			element having the @action="requery" attribute.  At this
			point, a new query is generated containing the data of
			the form.
		</xsd:documentation>
	</xsd:annotation>
	<xsd:import schemaLocation="Microsoft.Search.Types.xsd"
	            namespace="urn:Microsoft.Search.Types" />
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Root Element: Form                                -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:element name="Form">
		<xsd:annotation>
			<xsd:documentation>
				Forms are controls that allow users to refine their
				queries.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:group ref="NestedFormGroup">
					<xsd:annotation>
						<xsd:documentation>
							A collection of form controls.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:group>
				<xsd:element name="Frame" type="FrameType">
					<xsd:annotation>
						<xsd:documentation>
							A collection of form controls,
							displayed horizontally.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
			</xsd:choice>
			<xsd:attribute name="revision"
			               type="xsd:unsignedInt" use="optional">
				<xsd:annotation>
					<xsd:documentation>
						Unsigned integer indicating the revision of
						the schema used in the response.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="build"
			               type="t:String255" use="optional">
				<xsd:annotation>
					<xsd:documentation>
						The build of the component used to generate
						the response.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="rtl" type="xsd:boolean">
				<xsd:annotation>
					<xsd:documentation>
						If set to 'true' then the forms are
						right-to-left.  If set to 'false' then
						the forms are left-to-right.  If unspecified,
						the system will choose.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="propagate"
			               type="xsd:boolean" default="true">
				<xsd:annotation>
					<xsd:documentation>
						If set to 'false' then any changes to the
						main query box will be passed up with the
						requery generated by the Form, rather than
						passing the original query.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="separator"
			               type="xsd:boolean" default="false">
				<xsd:annotation>
					<xsd:documentation>
						If set to 'true' then the form block will
						display with a separator below it to
						distinguish it from other portions of the
						results.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Group: NestedFormGroup                            -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:group name="NestedFormGroup">
		<xsd:annotation>
			<xsd:documentation>
				Defines a collection of controls.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:choice>
			<xsd:element name="Button" type="ButtonType">
				<xsd:annotation>
					<xsd:documentation>
						A simple button.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Checkbox" type="CheckboxType">
				<xsd:annotation>
					<xsd:documentation>
						A checkbox.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Edit" type="EditType">
				<xsd:annotation>
					<xsd:documentation>
						An edit control.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Hyperlink" type="HyperlinkFormType">
				<xsd:annotation>
					<xsd:documentation>
						A hyperlink.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Label" type="TextType">
				<xsd:annotation>
					<xsd:documentation>
						A text label.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Listbox" type="ListboxType">
				<xsd:annotation>
					<xsd:documentation>
						A list box or dropdown control.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="NewQuery" type="NewQueryType">
				<xsd:annotation>
					<xsd:documentation>
						A new query control.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="RadioGroup" type="RadioGroupType">
				<xsd:annotation>
					<xsd:documentation>
						A radio button group.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:choice>
	</xsd:group>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Type: ButtonType                                  -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:complexType name="ButtonType">
		<xsd:annotation>
			<xsd:documentation>
				Defines a simple button.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Text" type="TextType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						The text for the control.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attributeGroup ref="ControlAttributes">
			<xsd:annotation>
				<xsd:documentation>
					Shared control attributes.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attributeGroup>
		<xsd:attribute name="tooltip"
		               type="t:String2048" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					Optional tooltip.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="icon" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					Optional icon, which suppresses the display
					of text.  Only the 'Go' icon is currently
					supported.
				</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="go" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Type: CheckboxType                                -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:complexType name="CheckboxType">
		<xsd:annotation>
			<xsd:documentation>
				Describes a checkbox control with optional
				child controls.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:all>
			<xsd:element name="Text" type="TextType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						The text of the checkbox.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Frame" type="FrameType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						Child elements under the checkbox.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:all>
		<xsd:attributeGroup ref="ControlAttributes">
			<xsd:annotation>
				<xsd:documentation>
					Shared control attributes.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attributeGroup>
		<xsd:attribute name="selected" type="xsd:boolean"
		               use="optional" default="false">
			<xsd:annotation>
				<xsd:documentation>
					If set to 'true' the checkbox appears checked.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Type: EditType                                    -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:complexType name="EditType">
		<xsd:annotation>
			<xsd:documentation>
				Describes an edit control with an optional label.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Text"
			             type="PositionalTextType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						Text for the control's label.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attributeGroup ref="ControlAttributes">
			<xsd:annotation>
				<xsd:documentation>
					Shared control attributes.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attributeGroup>
		<xsd:attribute name="value"
		               type="t:String2048" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					Initial text inside the control.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="password" type="xsd:boolean"
		               use="optional" default="false">
			<xsd:annotation>
				<xsd:documentation>
					If true, indicates that the edit control
					is a password box and needs to be obscured.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="rtl" type="xsd:boolean" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					If set to 'true' then the control is
					right-to-left.  If set to 'false' then
					the control is left-to-right.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="limit" use="optional" default="256">
			<xsd:annotation>
				<xsd:documentation>
					Maximum number of characters allowed.
				</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="1" />
					<xsd:maxInclusive value="4096" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="width" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					The width of the control in character units.
					If not specified, the control fills all
					available space.
				</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="1" />
					<xsd:maxInclusive value="128" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Type: HyperlinkFormType                           -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:complexType name="HyperlinkFormType">
		<xsd:annotation>
			<xsd:documentation>
				Defines a hyperlink that behaves like a button.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Text" type="TextType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						The text for the control.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attributeGroup ref="ControlAttributes">
			<xsd:annotation>
				<xsd:documentation>
					Shared control attributes.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attributeGroup>
		<xsd:attribute name="tooltip"
		               type="t:String2048" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					Optional tooltip.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Type: TextType                                    -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:complexType name="TextType">
		<xsd:annotation>
			<xsd:documentation>
				Defines a text label.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="rtl"
				               type="xsd:boolean" use="optional">
					<xsd:annotation>
						<xsd:documentation>
							If set to 'true' then the text is
							right-to-left.  If set to 'false'
							then the text is left-to-right.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Type: ListBoxType                                 -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:complexType name="ListboxType">
		<xsd:annotation>
			<xsd:documentation>
				Defines a list box control.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Text"
			             type="PositionalTextType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						The text for the control.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Option" type="ListBoxOptionType"
			             minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>
						An option in the listbox.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attributeGroup ref="ControlAttributes">
			<xsd:annotation>
				<xsd:documentation>
					Shared control attributes.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attributeGroup>
		<xsd:attribute name="dropdown"
		               type="xsd:boolean" use="optional" default="true">
			<xsd:annotation>
				<xsd:documentation>
					If set to 'false' then the control is a
					list box rather than a dropdown.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="rtl" type="xsd:boolean" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					If set to 'true' then the control is
					right-to-left.  If set to 'false' then the
					control is left-to-right.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="width" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					The width of the control in character units.
					If not specified, the control fills all
					available space.
				</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="1" />
					<xsd:maxInclusive value="128" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Type: ListBoxOptionType                           -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:complexType name="ListBoxOptionType">
		<xsd:annotation>
			<xsd:documentation>
				Defines an option in a list box.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:all>
			<xsd:element name="Text" type="xsd:string" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						Text for the option.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:all>
		<xsd:attribute name="id" type="t:IDType" use="required">
			<xsd:annotation>
				<xsd:documentation>
					Unique ID for the option.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="selected"
		               type="xsd:boolean" use="optional" default="false">
			<xsd:annotation>
				<xsd:documentation>
					If set to 'true' then the option is
					selected by default.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="level" use="optional" default="1">
			<xsd:annotation>
				<xsd:documentation>
					Indentation level for the option.
				</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:integer">
					<xsd:minInclusive value="1" />
					<xsd:maxInclusive value="3" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Type: NewQueryType                                -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:complexType name="NewQueryType">
		<xsd:annotation>
			<xsd:documentation>
				Defines a link that launches a new query.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Text" type="TextType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						The text for the link.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="query" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>
					The actual query to be sent when the link is
					clicked.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="tooltip"
		               type="t:String2048" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					An optional tooltip.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="category"
		               type="t:CategoryType" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					Category or group of services to be searched.
					If not specified, the currently selected set
					of services is searched.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="disabled" use="optional"
		               type="xsd:boolean" default="false">
			<xsd:annotation>
				<xsd:documentation>
					If set to 'true' the link is disabled.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Type: RadioGroupType                              -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:complexType name="RadioGroupType">
		<xsd:annotation>
			<xsd:documentation>
				Defines a group of radio buttons.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Text" type="TextType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						The text for the radio button group label.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Option" type="RadioOptionType"
			             minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>
						An individual radio button.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
		<xsd:attributeGroup ref="ControlAttributes">
			<xsd:annotation>
				<xsd:documentation>
					Shared control attributes.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attributeGroup>
		<xsd:attribute name="rtl" type="xsd:boolean">
			<xsd:annotation>
				<xsd:documentation>
					If set to 'true' then the radio button group is
					right-to-left.  If set to 'false' then the radio
					button group is left-to-right.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Type: RadioOptionType                             -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:complexType name="RadioOptionType">
		<xsd:annotation>
			<xsd:documentation>
				Defines an individual radio button.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:all>
			<xsd:element name="Text" type="TextType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						The text for the option.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Frame" type="FrameType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>
						Child elements under the radio button.
					</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:all>
		<xsd:attribute name="id" type="t:IDType" use="required">
			<xsd:annotation>
				<xsd:documentation>
					Unique ID for the option.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="selected" type="xsd:boolean"
		               use="optional" default="false">
			<xsd:annotation>
				<xsd:documentation>
					If set to 'true' then the option is
					selected by default.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="disabled" type="xsd:boolean"
		               use="optional" default="false">
			<xsd:annotation>
				<xsd:documentation>
					If set to 'true', the option is disabled.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Type: PositionalTextType                          -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:complexType name="PositionalTextType">
		<xsd:annotation>
			<xsd:documentation>
				Defines the text label for a control when the label
				may appear in different places with respect to the
				control.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="rtl" type="xsd:boolean">
					<xsd:annotation>
						<xsd:documentation>
							If set to 'true' then the text is
							right-to-left.  If set to 'false' then
							the text is left-to-right.
						</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
				<xsd:attribute name="position"
				               default="beside" use="optional">
					<xsd:annotation>
						<xsd:documentation>
							Describes where the text label is
							positioned relative to the control.
						</xsd:documentation>
					</xsd:annotation>
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="beside" />
							<xsd:enumeration value="above" />
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Type: FrameType                                   -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:complexType name="FrameType">
		<xsd:annotation>
			<xsd:documentation>
				Describes a group of controls that display
				side by side when possible.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:group ref="NestedFormGroup" />
		</xsd:sequence>
	</xsd:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Attribute Group: ControlAttributes                -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xsd:attributeGroup name="ControlAttributes">
		<xsd:annotation>
			<xsd:documentation>
				Defines attributes common to all Form controls.
			</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="id" type="t:IDType" use="required">
			<xsd:annotation>
				<xsd:documentation>
					The ID for the control.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="disabled" type="xsd:boolean"
		               use="optional" default="false">
			<xsd:annotation>
				<xsd:documentation>
					If set to 'true', the control is disabled.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="submitUrl"
		               type="xsd:anyURI" use="optional">
			<xsd:annotation>
				<xsd:documentation>
					The URL where the Form data will be submitted if
					the control is clicked and it has a requery
					action.  If absent, the service provider's
					registered Query Path is used.
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="action" use="optional" default="none">
			<xsd:annotation>
				<xsd:documentation>
					Action to perform.
				</xsd:documentation>
			</xsd:annotation>
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="requery">
						<xsd:annotation>
							<xsd:documentation>
								Will submit the Form data to the
								service and refresh the results
								with what the service returns.
							</xsd:documentation>
						</xsd:annotation>
					</xsd:enumeration>
					<xsd:enumeration value="none">
						<xsd:annotation>
							<xsd:documentation>
								Will not do anything, making the
								control able to change parameters
								but not submit the Form.
							</xsd:documentation>
						</xsd:annotation>
					</xsd:enumeration>
					<xsd:enumeration value="callback">
						<xsd:annotation>
							<xsd:documentation>
								Will submit the Form data to the
								service but will not expect any
								data back, which the service can
								use to call itself to perform an
								action.
							</xsd:documentation>
						</xsd:annotation>
					</xsd:enumeration>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:attributeGroup>
</xsd:schema>