//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToXsd.Schemas.XsdFeatureTests.ImportsXmlAttributes {
    using global::System;
    using global::System.Collections;
    using global::System.Collections.Generic;
    using global::System.ComponentModel;
    using global::System.IO;
    using global::System.Linq;
    using global::System.Diagnostics;
    using global::System.Xml;
    using global::System.Xml.Schema;
    using global::System.Xml.Linq;
    using global::Xml.Schema.Linq;
    using W3C.Xml1998;
    
    
    public partial class localAttributeGroupElementTest : XTypedElement, IXMetaData {
        
        public void Save(string xmlFile) {
            XTypedServices.Save(xmlFile, Untyped);
        }
        
        public void Save(System.IO.TextWriter tw) {
            XTypedServices.Save(tw, Untyped);
        }
        
        public void Save(System.Xml.XmlWriter xmlWriter) {
            XTypedServices.Save(xmlWriter, Untyped);
        }
        
        public static localAttributeGroupElementTest Load(string xmlFile) {
            return XTypedServices.Load<localAttributeGroupElementTest>(xmlFile);
        }
        
        public static localAttributeGroupElementTest Load(System.IO.TextReader xmlFile) {
            return XTypedServices.Load<localAttributeGroupElementTest>(xmlFile);
        }
        
        public static localAttributeGroupElementTest Parse(string xml) {
            return XTypedServices.Parse<localAttributeGroupElementTest>(xml);
        }
        
		public static explicit operator localAttributeGroupElementTest(XElement xe) { return XTypedServices.ToXTypedElement<localAttributeGroupElementTest>(xe,LinqToXsdTypeManager.Instance as ILinqToXsdTypeManager); }
        
        public override XTypedElement Clone() {
            return XTypedServices.CloneXTypedElement<localAttributeGroupElementTest>(this);
        }
        
        public localAttributeGroupElementTest() {
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        protected internal static readonly System.Xml.Linq.XName @baseXName = System.Xml.Linq.XName.Get("base", "http://www.w3.org/XML/1998/namespace");
        
        /// <summary>
        /// <para>
        /// Occurrence: optional
        /// </para>
        /// </summary>
        public virtual System.Uri @base {
            get {
                XAttribute x = this.Attribute(@baseXName);
                if ((x == null)) {
                    return null;
                }
                return XTypedServices.ParseValue<System.Uri>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.AnyUri).Datatype);
            }
            set {
                this.SetAttribute(@baseXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.AnyUri).Datatype);
            }
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        protected internal static readonly System.Xml.Linq.XName idXName = System.Xml.Linq.XName.Get("id", "http://www.w3.org/XML/1998/namespace");
        
        /// <summary>
        /// <para>
        /// Occurrence: optional
        /// </para>
        /// </summary>
        public virtual string id {
            get {
                XAttribute x = this.Attribute(idXName);
                if ((x == null)) {
                    return null;
                }
                return XTypedServices.ParseValue<string>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Id).Datatype);
            }
            set {
                this.SetAttribute(idXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Id).Datatype);
            }
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        protected internal static readonly System.Xml.Linq.XName langXName = System.Xml.Linq.XName.Get("lang", "http://www.w3.org/XML/1998/namespace");
        
        /// <summary>
        /// <para>
        /// Occurrence: optional
        /// </para>
        /// </summary>
        public virtual object lang {
            get {
                XAttribute x = this.Attribute(langXName);
                if ((x == null)) {
                    return null;
                }
                return XTypedServices.ParseUnionValue(x, global::W3C.Xml1998.lang.TypeDefinition);
            }
            set {
                this.SetUnionAttribute(value, "lang", this, langXName, global::W3C.Xml1998.lang.TypeDefinition);
            }
        }
        
        public enum SpaceEnum {
            
            @default,
            
            preserve,
        }
        
        public sealed class SpaceEnumValidator {
            
            private SpaceEnumValidator() {
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            public static global::Xml.Schema.Linq.SimpleTypeValidator TypeDefinition = new global::Xml.Schema.Linq.AtomicSimpleTypeValidator(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.NCName), new global::Xml.Schema.Linq.RestrictionFacets(((global::Xml.Schema.Linq.RestrictionFlags)(16)), new object[] {
                            "default:@default",
                            "preserve"}, 0, 0, null, null, 0, null, null, 0, null, 0, XmlSchemaWhiteSpace.Collapse));
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        protected internal static readonly System.Xml.Linq.XName spaceXName = System.Xml.Linq.XName.Get("space", "http://www.w3.org/XML/1998/namespace");
        
        /// <summary>
        /// <para>
        /// Occurrence: optional
        /// </para>
        /// </summary>
        public virtual LinqToXsd.Schemas.XsdFeatureTests.ImportsXmlAttributes.localAttributeGroupElementTest.SpaceEnum? space {
            get {
                XAttribute x = this.Attribute(spaceXName);
                if ((x == null)) {
                    return null;
                }
                return ((LinqToXsd.Schemas.XsdFeatureTests.ImportsXmlAttributes.localAttributeGroupElementTest.SpaceEnum)(Enum.Parse(typeof(LinqToXsd.Schemas.XsdFeatureTests.ImportsXmlAttributes.localAttributeGroupElementTest.SpaceEnum), XTypedServices.ParseValue(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.NCName).Datatype, SpaceEnumValidator.TypeDefinition))));
            }
            set {
                if (value == null) {
                    this.SetAttribute(spaceXName, null, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.NCName).Datatype);
                }
                else {
                    this.SetAttributeWithValidation(spaceXName, value.ToString(), "space", SpaceEnumValidator.TypeDefinition);
                }
            }
        }
        
        private static readonly System.Xml.Linq.XName xName = System.Xml.Linq.XName.Get("localAttributeGroupElementTest", "urn:LinqToXsd:Schemas:ImportsXmlAttributes");
        
        ContentModelEntity IXMetaData.GetContentModel() {
            return ContentModelEntity.Default;
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        System.Xml.Linq.XName IXMetaData.SchemaName {
            get {
                return xName;
            }
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        SchemaOrigin IXMetaData.TypeOrigin {
            get {
                return SchemaOrigin.Element;
            }
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILinqToXsdTypeManager IXMetaData.TypeManager {
            get {
                return LinqToXsdTypeManager.Instance;
            }
        }
        
        /// <summary>
        /// <para>
        /// This is an internal validation class.
        /// </para>
        /// </summary>
        private class simpleUnionTypeOfLanguageAnd {
            
            private simpleUnionTypeOfLanguageAnd() {
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            public static global::Xml.Schema.Linq.SimpleTypeValidator TypeDefinition = new global::Xml.Schema.Linq.UnionSimpleTypeValidator(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.AnyAtomicType), null, new global::Xml.Schema.Linq.SimpleTypeValidator[] {
                        new global::Xml.Schema.Linq.AtomicSimpleTypeValidator(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Language), null),
                        new global::Xml.Schema.Linq.AtomicSimpleTypeValidator(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String), new global::Xml.Schema.Linq.RestrictionFacets(((global::Xml.Schema.Linq.RestrictionFlags)(16)), new object[] {
                                        ""}, 0, 0, null, null, 0, null, null, 0, null, 0, XmlSchemaWhiteSpace.Preserve))});
        }
    }
    
    public partial class importedAttributeGroupElementTest : XTypedElement, IXMetaData {
        
        public void Save(string xmlFile) {
            XTypedServices.Save(xmlFile, Untyped);
        }
        
        public void Save(System.IO.TextWriter tw) {
            XTypedServices.Save(tw, Untyped);
        }
        
        public void Save(System.Xml.XmlWriter xmlWriter) {
            XTypedServices.Save(xmlWriter, Untyped);
        }
        
        public static importedAttributeGroupElementTest Load(string xmlFile) {
            return XTypedServices.Load<importedAttributeGroupElementTest>(xmlFile);
        }
        
        public static importedAttributeGroupElementTest Load(System.IO.TextReader xmlFile) {
            return XTypedServices.Load<importedAttributeGroupElementTest>(xmlFile);
        }
        
        public static importedAttributeGroupElementTest Parse(string xml) {
            return XTypedServices.Parse<importedAttributeGroupElementTest>(xml);
        }
        
		public static explicit operator importedAttributeGroupElementTest(XElement xe) { return XTypedServices.ToXTypedElement<importedAttributeGroupElementTest>(xe,LinqToXsdTypeManager.Instance as ILinqToXsdTypeManager); }
        
        public override XTypedElement Clone() {
            return XTypedServices.CloneXTypedElement<importedAttributeGroupElementTest>(this);
        }
        
        public importedAttributeGroupElementTest() {
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        protected internal static readonly System.Xml.Linq.XName @baseXName = System.Xml.Linq.XName.Get("base", "http://www.w3.org/XML/1998/namespace");
        
        /// <summary>
        /// <para>
        /// Occurrence: optional
        /// </para>
        /// </summary>
        public virtual System.Uri @base {
            get {
                XAttribute x = this.Attribute(@baseXName);
                if ((x == null)) {
                    return null;
                }
                return XTypedServices.ParseValue<System.Uri>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.AnyUri).Datatype);
            }
            set {
                this.SetAttribute(@baseXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.AnyUri).Datatype);
            }
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        protected internal static readonly System.Xml.Linq.XName langXName = System.Xml.Linq.XName.Get("lang", "http://www.w3.org/XML/1998/namespace");
        
        /// <summary>
        /// <para>
        /// Occurrence: optional
        /// </para>
        /// </summary>
        public virtual object lang {
            get {
                XAttribute x = this.Attribute(langXName);
                if ((x == null)) {
                    return null;
                }
                return XTypedServices.ParseUnionValue(x, global::W3C.Xml1998.lang.TypeDefinition);
            }
            set {
                this.SetUnionAttribute(value, "lang", this, langXName, global::W3C.Xml1998.lang.TypeDefinition);
            }
        }
        
        public enum SpaceEnum {
            
            @default,
            
            preserve,
        }
        
        public sealed class SpaceEnumValidator {
            
            private SpaceEnumValidator() {
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            public static global::Xml.Schema.Linq.SimpleTypeValidator TypeDefinition = new global::Xml.Schema.Linq.AtomicSimpleTypeValidator(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.NCName), new global::Xml.Schema.Linq.RestrictionFacets(((global::Xml.Schema.Linq.RestrictionFlags)(16)), new object[] {
                            "default:@default",
                            "preserve"}, 0, 0, null, null, 0, null, null, 0, null, 0, XmlSchemaWhiteSpace.Collapse));
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        protected internal static readonly System.Xml.Linq.XName spaceXName = System.Xml.Linq.XName.Get("space", "http://www.w3.org/XML/1998/namespace");
        
        /// <summary>
        /// <para>
        /// Occurrence: optional
        /// </para>
        /// </summary>
        public virtual LinqToXsd.Schemas.XsdFeatureTests.ImportsXmlAttributes.importedAttributeGroupElementTest.SpaceEnum? space {
            get {
                XAttribute x = this.Attribute(spaceXName);
                if ((x == null)) {
                    return null;
                }
                return ((LinqToXsd.Schemas.XsdFeatureTests.ImportsXmlAttributes.importedAttributeGroupElementTest.SpaceEnum)(Enum.Parse(typeof(LinqToXsd.Schemas.XsdFeatureTests.ImportsXmlAttributes.importedAttributeGroupElementTest.SpaceEnum), XTypedServices.ParseValue(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.NCName).Datatype, SpaceEnumValidator.TypeDefinition))));
            }
            set {
                if (value == null) {
                    this.SetAttribute(spaceXName, null, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.NCName).Datatype);
                }
                else {
                    this.SetAttributeWithValidation(spaceXName, value.ToString(), "space", SpaceEnumValidator.TypeDefinition);
                }
            }
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        protected internal static readonly System.Xml.Linq.XName idXName = System.Xml.Linq.XName.Get("id", "http://www.w3.org/XML/1998/namespace");
        
        /// <summary>
        /// <para>
        /// Occurrence: optional
        /// </para>
        /// </summary>
        public virtual string id {
            get {
                XAttribute x = this.Attribute(idXName);
                if ((x == null)) {
                    return null;
                }
                return XTypedServices.ParseValue<string>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Id).Datatype);
            }
            set {
                this.SetAttribute(idXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Id).Datatype);
            }
        }
        
        private static readonly System.Xml.Linq.XName xName = System.Xml.Linq.XName.Get("importedAttributeGroupElementTest", "urn:LinqToXsd:Schemas:ImportsXmlAttributes");
        
        ContentModelEntity IXMetaData.GetContentModel() {
            return ContentModelEntity.Default;
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        System.Xml.Linq.XName IXMetaData.SchemaName {
            get {
                return xName;
            }
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        SchemaOrigin IXMetaData.TypeOrigin {
            get {
                return SchemaOrigin.Element;
            }
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILinqToXsdTypeManager IXMetaData.TypeManager {
            get {
                return LinqToXsdTypeManager.Instance;
            }
        }
        
        /// <summary>
        /// <para>
        /// This is an internal validation class.
        /// </para>
        /// </summary>
        private class simpleUnionTypeOfLanguageAnd {
            
            private simpleUnionTypeOfLanguageAnd() {
            }
            
            [DebuggerBrowsable(DebuggerBrowsableState.Never)]
            public static global::Xml.Schema.Linq.SimpleTypeValidator TypeDefinition = new global::Xml.Schema.Linq.UnionSimpleTypeValidator(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.AnyAtomicType), null, new global::Xml.Schema.Linq.SimpleTypeValidator[] {
                        new global::Xml.Schema.Linq.AtomicSimpleTypeValidator(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Language), null),
                        new global::Xml.Schema.Linq.AtomicSimpleTypeValidator(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String), new global::Xml.Schema.Linq.RestrictionFacets(((global::Xml.Schema.Linq.RestrictionFlags)(16)), new object[] {
                                        ""}, 0, 0, null, null, 0, null, null, 0, null, 0, XmlSchemaWhiteSpace.Preserve))});
        }
    }
    
    public class LinqToXsdTypeManager : ILinqToXsdTypeManager {
        
        private LinqToXsdTypeManager() {
        }
        
        private static Dictionary<System.Xml.Linq.XName, System.Type> elementDictionary = new Dictionary<System.Xml.Linq.XName, System.Type>();
        
        private static void BuildElementDictionary() {
            elementDictionary.Add(System.Xml.Linq.XName.Get("localAttributeGroupElementTest", "urn:LinqToXsd:Schemas:ImportsXmlAttributes"), typeof(global::LinqToXsd.Schemas.XsdFeatureTests.ImportsXmlAttributes.localAttributeGroupElementTest));
            elementDictionary.Add(System.Xml.Linq.XName.Get("importedAttributeGroupElementTest", "urn:LinqToXsd:Schemas:ImportsXmlAttributes"), typeof(global::LinqToXsd.Schemas.XsdFeatureTests.ImportsXmlAttributes.importedAttributeGroupElementTest));
        }
        
        private static XmlSchemaSet schemaSet;
        
        XmlSchemaSet ILinqToXsdTypeManager.Schemas {
            get {
                if ((schemaSet == null)) {
                    XmlSchemaSet tempSet = new XmlSchemaSet();
                    System.Threading.Interlocked.CompareExchange(ref schemaSet, tempSet, null);
                }
                return schemaSet;
            }
            set {
                schemaSet = value;
            }
        }
        
        protected internal static void AddSchemas(XmlSchemaSet schemas) {
            schemas.Add(schemaSet);
        }
        
        Dictionary<System.Xml.Linq.XName, System.Type> ILinqToXsdTypeManager.GlobalTypeDictionary {
            get {
                return XTypedServices.EmptyDictionary;
            }
        }
        
        Dictionary<System.Xml.Linq.XName, System.Type> ILinqToXsdTypeManager.GlobalElementDictionary {
            get {
                return elementDictionary;
            }
        }
        
        Dictionary<System.Type, System.Type> ILinqToXsdTypeManager.RootContentTypeMapping {
            get {
                return XTypedServices.EmptyTypeMappingDictionary;
            }
        }
        
        static LinqToXsdTypeManager() {
            BuildElementDictionary();
        }
        
        public static System.Type GetRootType() {
            return elementDictionary[System.Xml.Linq.XName.Get("localAttributeGroupElementTest", "urn:LinqToXsd:Schemas:ImportsXmlAttributes")];
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private static LinqToXsdTypeManager typeManagerSingleton = new LinqToXsdTypeManager();
        
        public static LinqToXsdTypeManager Instance {
            get {
                return typeManagerSingleton;
            }
        }
    }
    
    public partial class XRootNamespace {
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private XDocument doc;
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private XTypedElement rootObject;
        
        private XRootNamespace() {
        }
        
        public static XRootNamespace Load(string xmlFile) {
            XRootNamespace root = new XRootNamespace();
            root.doc = XDocument.Load(xmlFile);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRootNamespace Load(string xmlFile, LoadOptions options) {
            XRootNamespace root = new XRootNamespace();
            root.doc = XDocument.Load(xmlFile, options);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRootNamespace Load(TextReader textReader) {
            XRootNamespace root = new XRootNamespace();
            root.doc = XDocument.Load(textReader);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRootNamespace Load(TextReader textReader, LoadOptions options) {
            XRootNamespace root = new XRootNamespace();
            root.doc = XDocument.Load(textReader, options);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRootNamespace Load(XmlReader xmlReader) {
            XRootNamespace root = new XRootNamespace();
            root.doc = XDocument.Load(xmlReader);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRootNamespace Parse(string text) {
            XRootNamespace root = new XRootNamespace();
            root.doc = XDocument.Parse(text);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRootNamespace Parse(string text, LoadOptions options) {
            XRootNamespace root = new XRootNamespace();
            root.doc = XDocument.Parse(text, options);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public virtual void Save(string fileName) {
            doc.Save(fileName);
        }
        
        public virtual void Save(TextWriter textWriter) {
            doc.Save(textWriter);
        }
        
        public virtual void Save(XmlWriter writer) {
            doc.Save(writer);
        }
        
        public virtual void Save(TextWriter textWriter, SaveOptions options) {
            doc.Save(textWriter, options);
        }
        
        public virtual void Save(string fileName, SaveOptions options) {
            doc.Save(fileName, options);
        }
        
        public virtual XDocument XDocument {
            get {
                return doc;
            }
        }
        
        public virtual XTypedElement Root {
            get {
                return rootObject;
            }
        }
        
        public XRootNamespace(localAttributeGroupElementTest root) {
            this.doc = new XDocument(root.Untyped);
            this.rootObject = root;
        }
        

		public localAttributeGroupElementTest localAttributeGroupElementTest {  get {return rootObject as localAttributeGroupElementTest; } }
        
        public XRootNamespace(importedAttributeGroupElementTest root) {
            this.doc = new XDocument(root.Untyped);
            this.rootObject = root;
        }
        

		public importedAttributeGroupElementTest importedAttributeGroupElementTest {  get {return rootObject as importedAttributeGroupElementTest; } }
    }
    
    public partial class XRoot {
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private XDocument doc;
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private XTypedElement rootObject;
        
        private XRoot() {
        }
        
        public static XRoot Load(string xmlFile) {
            XRoot root = new XRoot();
            root.doc = XDocument.Load(xmlFile);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRoot Load(string xmlFile, LoadOptions options) {
            XRoot root = new XRoot();
            root.doc = XDocument.Load(xmlFile, options);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRoot Load(TextReader textReader) {
            XRoot root = new XRoot();
            root.doc = XDocument.Load(textReader);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRoot Load(TextReader textReader, LoadOptions options) {
            XRoot root = new XRoot();
            root.doc = XDocument.Load(textReader, options);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRoot Load(XmlReader xmlReader) {
            XRoot root = new XRoot();
            root.doc = XDocument.Load(xmlReader);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRoot Parse(string text) {
            XRoot root = new XRoot();
            root.doc = XDocument.Parse(text);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public static XRoot Parse(string text, LoadOptions options) {
            XRoot root = new XRoot();
            root.doc = XDocument.Parse(text, options);
            XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
            if ((typedRoot == null)) {
                throw new LinqToXsdException("Invalid root element in xml document.");
            }
            root.rootObject = typedRoot;
            return root;
        }
        
        public virtual void Save(string fileName) {
            doc.Save(fileName);
        }
        
        public virtual void Save(TextWriter textWriter) {
            doc.Save(textWriter);
        }
        
        public virtual void Save(XmlWriter writer) {
            doc.Save(writer);
        }
        
        public virtual void Save(TextWriter textWriter, SaveOptions options) {
            doc.Save(textWriter, options);
        }
        
        public virtual void Save(string fileName, SaveOptions options) {
            doc.Save(fileName, options);
        }
        
        public virtual XDocument XDocument {
            get {
                return doc;
            }
        }
        
        public virtual XTypedElement Root {
            get {
                return rootObject;
            }
        }
        
        public XRoot(global::LinqToXsd.Schemas.XsdFeatureTests.ImportsXmlAttributes.localAttributeGroupElementTest root) {
            this.doc = new XDocument(root.Untyped);
            this.rootObject = root;
        }
        

		public global::LinqToXsd.Schemas.XsdFeatureTests.ImportsXmlAttributes.localAttributeGroupElementTest localAttributeGroupElementTest {  get {return rootObject as global::LinqToXsd.Schemas.XsdFeatureTests.ImportsXmlAttributes.localAttributeGroupElementTest; } }
        
        public XRoot(global::LinqToXsd.Schemas.XsdFeatureTests.ImportsXmlAttributes.importedAttributeGroupElementTest root) {
            this.doc = new XDocument(root.Untyped);
            this.rootObject = root;
        }
        

		public global::LinqToXsd.Schemas.XsdFeatureTests.ImportsXmlAttributes.importedAttributeGroupElementTest importedAttributeGroupElementTest {  get {return rootObject as global::LinqToXsd.Schemas.XsdFeatureTests.ImportsXmlAttributes.importedAttributeGroupElementTest; } }
    }
}
namespace W3C.Xml1998 {
    using global::System;
    using global::System.Collections;
    using global::System.Collections.Generic;
    using global::System.ComponentModel;
    using global::System.IO;
    using global::System.Linq;
    using global::System.Diagnostics;
    using global::System.Xml;
    using global::System.Xml.Schema;
    using global::System.Xml.Linq;
    using global::Xml.Schema.Linq;
    using LinqToXsd.Schemas.XsdFeatureTests.ImportsXmlAttributes;
    
    
    public sealed class lang {
        
        private lang() {
        }
        
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        public static global::Xml.Schema.Linq.SimpleTypeValidator TypeDefinition = new global::Xml.Schema.Linq.UnionSimpleTypeValidator(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.AnyAtomicType), null, new global::Xml.Schema.Linq.SimpleTypeValidator[] {
                    new global::Xml.Schema.Linq.AtomicSimpleTypeValidator(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Language), null),
                    new global::Xml.Schema.Linq.AtomicSimpleTypeValidator(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String), new global::Xml.Schema.Linq.RestrictionFacets(((global::Xml.Schema.Linq.RestrictionFlags)(16)), new object[] {
                                    ""}, 0, 0, null, null, 0, null, null, 0, null, 0, XmlSchemaWhiteSpace.Preserve))});
    }
}
