//Copyright (c) Microsoft Corporation.  All rights reserved.

using System;
using System.Xml;
using System.Xml.Schema;
using System.Collections.Generic;
using System.CodeDom;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using Xml.Schema.Linq.CodeGen.Model;
using Xml.Schema.Linq.Extensions;
using XObjects;

namespace Xml.Schema.Linq.CodeGen
{
    public class CodeDomTypesGenerator
    {
        readonly LinqToXsdSettings settings;
        TypeBuilder typeBuilder;

        // TODO: eventually remove
        XmlQualifiedName rootElementName = XmlQualifiedName.Empty;
        public CClass RootElement { get; private set; }
        public IEnumerable<CClass> AllRoots => codeNamespacesTable.Values.SelectMany(ns => ns.Roots);

        CNamespace cNamespace, rootNamespace;
        public CNamespace RootNamespace => rootNamespace;

        readonly Dictionary<string, CNamespace> codeNamespacesTable = new();
        Dictionary<XmlSchemaObject, string> nameMappings;
        readonly List<ClrWrapperTypeInfo> wrapperRootElements = [];

        string currentNamespace;
        string currentFullTypeName;

        public readonly List<CElement> AllTypes = [];        
        // TODO: review naming, this is more an AllTypes than AllElements as it also contains wrapper classes for simple types
        //       but then what's the difference with AllTypes above? is AllElements only the non-nested types? 
        //       I guess I'll figure it out after migrating more code.
        public readonly List<CClass> AllElements = [];
        public readonly List<KeyValuePair<string, string>> AllWrappers = [];

        public CodeDomTypesGenerator(LinqToXsdSettings settings)
        {
            this.settings = settings
                ?? throw new ArgumentNullException(nameof(settings));
        }

        public IEnumerable<CNamespace> GenerateTypes(ClrMappingInfo binding)
        {
            if (binding == null) throw new ArgumentNullException(nameof(binding));

            nameMappings = binding.NameMappings;
            Debug.Assert(nameMappings != null);

            foreach (ClrTypeInfo type in binding.Types)
            {
                if (type.IsWrapper)
                {
                    wrapperRootElements.Add(type as ClrWrapperTypeInfo);
                    continue;
                }
                
                cNamespace = GetCNamespace(type.clrtypeNs);
                Debug.Assert(cNamespace != null);                

                if (type is ClrSimpleTypeInfo stInfo)
                {
                    if (stInfo is EnumSimpleTypeInfo enumTypeInfo)
                    {
                        // The following is already generated in simple type template
                        // var enumType = TypeBuilder.CreateEnumType(enumTypeInfo, settings, stInfo);
                        // cNamespace.Add(enumType); // Enum declaration is generated by simple type template at the same time as validator
                        var enumType = new CodeTypeDeclaration(enumTypeInfo.clrtypeName) { IsEnum = true };

                        // TODO: Figure out how where descendant enum declarations could be generated
                        //       and ensure template doesn't generate them twice.
                        var ns = cNamespace.Dom;
                        var enumsInOtherTypes = ns.DescendentTypeScopedEnumDeclarations();
                        // if an enum is defined in another type, remove it, if it is the same as the global (namespace scoped type)
                        if (enumsInOtherTypes.EqualEnumDeclarationExists(enumType)) 
                        {
                            var typeWithDuplicateEnum = ns.TypeWithEnumDeclaration(enumType);
                            var duplicateEnum = typeWithDuplicateEnum.Members.OfType<CodeTypeDeclaration>()
                                .First(c => c.IsEqualEnumDeclaration(enumType));
                            typeWithDuplicateEnum.Members.Remove(duplicateEnum);
                        }
                    }

                    cNamespace.Add(new CSimpleType(stInfo, nameMappings, settings));
                }
                else 
                {
                    // TODO: no it doesn't set cNamespace? (anymore?)
                    var element = ProcessType2(type as ClrContentTypeInfo, cNamespace); // Sets current cNamespace as side-effet

                    if (type.typeOrigin == SchemaOrigin.Element)
                    {
                        cNamespace.Roots.Add(element);
                        UpdateRootElement(type, element);
                    }
                }
            }

            ProcessWrapperTypes();
            FindRootNamespace();

            return codeNamespacesTable.Values;
        }

        private CElement ProcessType2(ClrContentTypeInfo typeInfo, IHasTypes parent)
        {
            bool globalType = parent is CNamespace;
            SetFullTypeName(typeInfo, parent is CElement p ? p.Fqn : null);

            if (globalType)
                currentNamespace = typeInfo.clrtypeNs;  // dependent on SetFullTypeName above

            var element = new CElement(typeInfo);
            parent.Add(element);

            foreach (var content in typeInfo.Content) 
            {
                if (content is ClrPropertyInfo info)
                {
                    // TODO: review handling of createNestedEnumType action
                    info.UpdateTypeReference(currentFullTypeName, currentNamespace, nameMappings, (_) => {});
                }
            }

            if (globalType) 
            {
                if (typeInfo.typeOrigin == SchemaOrigin.Fragment)
                    AllTypes.Add(element);
                else
                    AllElements.Add(element);
            }

            ProcessNestedTypes(typeInfo.NestedTypes, element);

            return element;
        }

        private void ProcessNestedTypes(List<ClrTypeInfo> anonymousTypes, CElement parent)
        {
            foreach (ClrTypeInfo nestedType in anonymousTypes) 
            {
                // TODO: check if enum is already declared
                if (false && nestedType is EnumSimpleTypeInfo && EnumAlreadyExistsInParent(nestedType.clrtypeName, null)) // null -> [CodeTypeDeclaration]parentTypeDecl)) 
                   continue;

                CClass element;
                if (nestedType is ClrSimpleTypeInfo simpleType) 
                    parent.Add(new CSimpleType(simpleType, nameMappings, settings));
                else
                    element = ProcessType2(nestedType as ClrContentTypeInfo, parent);
            }
        }

        private CodeTypeDeclaration ProcessType(ClrContentTypeInfo typeInfo, string parentIdentifier, bool globalType)
        {
            SetFullTypeName(typeInfo, parentIdentifier);

            if (globalType)
                currentNamespace = typeInfo.clrtypeNs;  // dependent on SetFullTypeName above

            // Build type using TypeBuilder
            typeBuilder = GetTypeBuilder();
            typeBuilder.CreateTypeDeclaration(typeInfo, cNamespace.Dom);
            ProcessProperties(typeInfo.Content, typeInfo.Annotations);
            typeBuilder.CreateFunctionalConstructor(typeInfo.Annotations);
            typeBuilder.ImplementInterfaces(settings.EnableServiceReference);

            CodeTypeDeclaration builtType = typeBuilder.TypeDeclaration;
            
            if (globalType)
            {
                // TODO: these shouldn't be a new instances but the instance built above by TypeBuilder, when migrated
                // if (typeInfo.typeOrigin == SchemaOrigin.Fragment)
                //     AllTypes.Add(new() 
                //     { 
                //         Name = typeInfo.clrFullTypeName, 
                //         XsdName = typeInfo.schemaName, 
                //         XsdNs = typeInfo.schemaNs,
                //     });
                // else
                //     AllElements.Add(new() 
                //     {
                //         Dom = builtType,
                //         Name = typeInfo.clrFullTypeName,
                //         XsdName = typeInfo.schemaName,
                //         XsdNs = typeInfo.schemaNs,
                //     });
            }

            // ProcessNestedTypes(typeInfo.NestedTypes, builtType, typeInfo.clrFullTypeName);
            return builtType;
        }

        private void ProcessProperties(IEnumerable<ContentInfo> properties, List<ClrAnnotation> annotations)
        {
            foreach (ContentInfo child in properties)
            {
                //Child can either be a property directly for attributes or a grouping for content model,
                if (child.ContentType == ContentType.Property)
                {
                    ClrPropertyInfo propertyInfo = child as ClrPropertyInfo;
                    Debug.Assert(propertyInfo is not null);
                    propertyInfo.UpdateTypeReference(currentFullTypeName, currentNamespace, nameMappings, CreateNestedEnumType);
                    typeBuilder.CreateAttributeProperty(propertyInfo, null);
                }
                else
                {
                    GroupingInfo rootGroup = child as GroupingInfo;
                    if (rootGroup.IsComplex)
                    {
                        typeBuilder.StartGrouping(rootGroup);
                        ProcessComplexGroupProperties(rootGroup, annotations);
                        typeBuilder.EndGrouping();
                    }
                    else
                    {
                        ProcessGroup(rootGroup, annotations);
                    }
                }
            }
        }

        private void CreateNestedEnumType(ClrTypeReference typeRef)
        {
            if (typeRef == null) throw new ArgumentNullException(nameof(typeRef));
            var parentDecl = typeBuilder.TypeDeclaration;
            if (EnumAlreadyExistsInParent(typeRef.Name, parentDecl))
            {
                //If the enum type is already defined in the parent type, do not create it again
                return;
            }

            var innerType = typeRef.SchemaObject as XmlSchemaSimpleType;
            Debug.Assert(innerType != null);
            var visibilitySetting = this.settings.NamespaceTypesVisibilityMap.ValueForKey(typeRef.Namespace);
            var enumTypeDecl = new CodeTypeDeclaration(typeRef.Name) {
                IsEnum = true,
                TypeAttributes = visibilitySetting.ToTypeAttribute()
            };
            foreach (var facet in innerType.GetEnumFacets()) {
                enumTypeDecl.Members.Add(new CodeMemberField(typeRef.Name, facet.Member));
            }

            enumTypeDecl.UserData[nameof(ClrTypeReference)] = typeRef;

            //Create enum validator type
            var enumTypeInfo = new EnumSimpleTypeInfo(innerType) { clrtypeName = typeRef.Name, clrtypeNs = string.Empty };
            var enumValidatorDecl = TypeBuilder.CreateSimpleType(enumTypeInfo, nameMappings, settings);

            parentDecl.Members.Add(enumTypeDecl);
            parentDecl.Members.Add(enumValidatorDecl);
        }

        private static bool EnumAlreadyExistsInParent(string clrEnumTypeName, CodeTypeDeclaration parent)
        {
            return parent.Members
                .OfType<CodeTypeDeclaration>()
                .Any(m => m.IsEnum && m.Name == clrEnumTypeName);
        }

        private void ProcessGroup(GroupingInfo grouping, List<ClrAnnotation> annotations)
        {
            typeBuilder.StartGrouping(grouping);
            foreach (ContentInfo child in grouping.Children)
            {
                if (child.ContentType == ContentType.Property)
                {
                    ClrPropertyInfo propertyInfo = child as ClrPropertyInfo;
                    propertyInfo.UpdateTypeReference(currentFullTypeName, currentNamespace, nameMappings, CreateNestedEnumType);
                    typeBuilder.CreateProperty(propertyInfo, annotations);
                }
                else if (child.ContentType == ContentType.WildCardProperty)
                {
                    ClrWildCardPropertyInfo propertyInfo = child as ClrWildCardPropertyInfo;
                    typeBuilder.CreateProperty(propertyInfo, annotations);
                }
                else
                {
                    Debug.Assert(child.ContentType == ContentType.Grouping);
                    ProcessGroup(child as GroupingInfo, annotations);
                }
            }

            typeBuilder.EndGrouping();
        }

        private void ProcessComplexGroupProperties(GroupingInfo grouping, List<ClrAnnotation> annotations)
        {
            foreach (ContentInfo child in grouping.Children)
            {
                if (child.ContentType == ContentType.Property)
                {
                    ClrPropertyInfo propertyInfo = child as ClrPropertyInfo;
                    propertyInfo.UpdateTypeReference(currentFullTypeName, currentNamespace, nameMappings, CreateNestedEnumType);
                    typeBuilder.CreateProperty(propertyInfo, annotations);
                }
                else if (child.ContentType == ContentType.WildCardProperty)
                {
                    ClrWildCardPropertyInfo propertyInfo = child as ClrWildCardPropertyInfo;
                    typeBuilder.CreateProperty(propertyInfo, annotations);
                }
                else
                {
                    Debug.Assert(child.ContentType == ContentType.Grouping);
                    typeBuilder.StartGrouping(child as GroupingInfo);
                    ProcessComplexGroupProperties(child as GroupingInfo, annotations);
                    typeBuilder.EndGrouping();
                }
            }
        }

        private void FindRootNamespace()
        {
            string rootClrNamespace = settings.GetClrNamespace(rootElementName.Namespace);
            if (!codeNamespacesTable.TryGetValue(rootClrNamespace, out rootNamespace))
            {
                // This might happen if the schema set has no global elements and only global types then you can create a root tag with xsi:type
                rootNamespace = codeNamespacesTable.Values.FirstOrDefault(); 
                // rootCodeNamespace may still be null if schema has only simple typed global elements or simple types which we are ignoring for now
            }
        }

        private void ProcessWrapperTypes()
        {
            if (wrapperRootElements.Count == 0) return;

            var wrapperBuilder = new XWrapperTypedElementBuilder(settings);
            foreach (ClrWrapperTypeInfo typeInfo in wrapperRootElements)
            {
                CClass cType = null;
                SetFullTypeName(typeInfo, null);
                ClrTypeReference innerType = typeInfo.InnerType;
                if (innerType.IsSimpleType)
                {
                    // TODO: this contains a `CreateNestedEnumType` that creates an enum Declaration,
                    //       see TODO in ClrPropertyInfo.UpdateTypeReference
                    var typedValueProperty = InitializeTypedValuePropertyInfo(typeInfo, innerType);
                    typedValueProperty.SetFixedDefaultValue(typeInfo);
                    // TODO review? Did it by example for now
                    // simpleTypeBuilder.ImplementInterfaces(settings.EnableServiceReference);
                    cType = new CSimpleTypeWrapper(typeInfo, typedValueProperty);
                    AllElements.Add(cType);
                }
                else
                {
                    string innerTypeName = null;
                    string innerTypeFullName =
                        innerType.GetClrFullTypeName(typeInfo.clrtypeNs, nameMappings, settings, out innerTypeName);
                    string innerTypeNs = innerType.Namespace;

                    CodeNamespace innerTypeCodeNamespace = GetCodeNamespace(innerTypeNs);
                    CodeTypeDeclaration innerTypeDecl = GetCodeTypeDeclaration(innerTypeName, innerTypeCodeNamespace);
                    TypeAttributes innerTypeAttributes = TypeAttributes.Class;
                    if (innerTypeDecl != null)
                    {
                        innerTypeAttributes = innerTypeDecl.TypeAttributes;
                    }
                    else if (innerTypeName != Constants.XTypedElement)
                    {
                        continue;
                    }

                    currentNamespace = typeInfo.clrtypeNs;
                    wrapperBuilder.Init(innerTypeFullName, innerTypeNs, innerTypeAttributes);
                    wrapperBuilder.CreateTypeDeclaration(typeInfo, cNamespace.Dom);
                    wrapperBuilder.CreateFunctionalConstructor(typeInfo.Annotations);
                    wrapperBuilder.ApplyAnnotations(typeInfo);

                    // TODO: shouldn't be a new instance but rather from wrapperBuilder when migrated
                    // AllElements.Add(new() 
                    // {
                    //     Dom = wrapperBuilder.TypeDeclaration,
                    //     Name = typeInfo.clrFullTypeName,
                    //     XsdName = typeInfo.schemaName,
                    //     XsdNs = typeInfo.schemaNs,
                    // });

                    AllWrappers.Add(new(typeInfo.clrFullTypeName, innerTypeFullName));

                    if (!typeInfo.HasBaseContentType)
                    {
                        //Add innerType properties only if the wrapper's type is not the same as the substitutionGroup head type
                        ClrWrappingPropertyInfo wrappingPropertyInfo = null;
                        //Create forwarding properties
                        if (innerTypeName != Constants.XTypedElement)
                        {
                            //If the wrapped type is xs:anyType, no forwarding properties to create
                            wrappingPropertyInfo = new ClrWrappingPropertyInfo();

                            //Get all properties from the inner type and its base types
                            var memberProperties = innerTypeDecl
                                .GetSelfAndBaseMembers(GetCodeNamespace, GetCodeTypeDeclaration)
                                .OfType<CodeMemberProperty>()
                                .ToArray();

                            foreach (CodeMemberProperty memberProperty in memberProperties)
                            {
                                if (ForwardProperty(memberProperty))
                                {
                                    //Do not forward over TypeManager, SchemaName etc
                                    wrappingPropertyInfo.Init(memberProperty);
                                    wrapperBuilder.CreateProperty(wrappingPropertyInfo, typeInfo.Annotations);
                                }
                            }
                        }
                    }
                    wrapperBuilder.ImplementInterfaces(settings.EnableServiceReference);
                }

                cNamespace = GetCNamespace(typeInfo.clrtypeNs);
                if (cType != null)  // TODO: temporary
                {
                    cNamespace.AddWrapper(cType);
                    cNamespace.Roots.Add(cType);
                    if (typeInfo.typeOrigin == SchemaOrigin.Element) 
                        UpdateRootElement(typeInfo, cType);
                }
            }
        }

        private bool ForwardProperty(CodeMemberProperty property)
        {
            return property != null && property.ImplementationTypes.Count == 0; //Its not an interface impl (IXMetaData)
        }

        private CodeTypeDeclaration GetCodeTypeDeclaration(string typeName, CodeNamespace innerTypeCodeNamespace)
        {
            if (innerTypeCodeNamespace == null)
            {
                return null;
            }

            CodeTypeDeclarationCollection types = innerTypeCodeNamespace.Types;
            foreach (CodeTypeDeclaration decl in types)
            {
                if (decl.Name.Equals(typeName))
                {
                    return decl;
                }
            }

            return null;
        }

        private TypeBuilder GetTypeBuilder()
        {
            if (typeBuilder == null)
                typeBuilder = new XTypedElementBuilder(settings, cNamespace.Dom);
            else
                typeBuilder.Init();

            return typeBuilder;
        }

        private void SetFullTypeName(ClrTypeInfo typeInfo, string parentIdentifier)
        {
            currentFullTypeName = parentIdentifier != null
                ? parentIdentifier + "." + typeInfo.clrtypeName
                : typeInfo.clrtypeNs != ""
                    ? typeInfo.clrtypeNs + "." + typeInfo.clrtypeName
                    : typeInfo.clrtypeName;

            typeInfo.clrFullTypeName = currentFullTypeName;
            XmlQualifiedName baseTypeName = typeInfo.BaseTypeName;
            if (baseTypeName != XmlQualifiedName.Empty)
            {
                string clrNamespace = settings.GetClrNamespace(baseTypeName.Namespace);
                if (nameMappings.TryGetValue(typeInfo.baseType, out string baseTypeIdentifier))
                {
                    typeInfo.baseTypeClrName = baseTypeIdentifier;
                    typeInfo.baseTypeClrNs = clrNamespace;
                }
            }

            if (typeInfo.typeOrigin == SchemaOrigin.Element && (rootElementName.IsEmpty || typeInfo.IsRoot))
                rootElementName = new XmlQualifiedName(typeInfo.schemaName, typeInfo.schemaNs);
        }

        private void UpdateRootElement(ClrTypeInfo info, CClass decl)
        {
            // The last IsRoot element is assumed to be the schema root element
            // When there is no IsRoot element, then the first element in schema is the assumed root.
            if (info.IsRoot)
                RootElement = decl;
            else
                RootElement ??= decl;
        }

        private ClrPropertyInfo InitializeTypedValuePropertyInfo(ClrTypeInfo typeInfo, ClrTypeReference innerType)
        {

            var propInfo = new ClrPropertyInfo(
                Constants.SInnerTypePropertyName, 
                string.Empty,
                Constants.SInnerTypePropertyName, 
                Occurs.One, 
                settings) 
            {                    
                Origin = SchemaOrigin.Text,
                TypeReference = innerType,
                IsNew = typeInfo.IsSubstitutionMember(),
            };
            propInfo.UpdateTypeReference(currentFullTypeName, currentNamespace, nameMappings, CreateNestedEnumType);
            return propInfo;
        }
        
        private CNamespace GetCNamespace(string clrNamespace)
        {
            if (cNamespace?.Name == clrNamespace)
                return cNamespace;

            if (!codeNamespacesTable.TryGetValue(clrNamespace, out CNamespace currentCodeNamespace))
            {
                currentCodeNamespace = new CNamespace(clrNamespace)
                {
                    Dom = new CodeNamespace(clrNamespace),
                    AccessModifier = settings.NamespaceTypesVisibilityMap
                        .GetValueOrDefault(clrNamespace, GeneratedTypesVisibility.Public)
                        .ToKeyword(),
                };
                codeNamespacesTable.Add(clrNamespace, currentCodeNamespace);
            }

            return currentCodeNamespace;
        }

        private CodeNamespace GetCodeNamespace(string clrNamespace) => GetCNamespace(clrNamespace).Dom;
    }
}