//Copyright (c) Microsoft Corporation.  All rights reserved.

using System;
using System.Xml;
using System.Xml.Schema;
using System.Collections.Generic;
using System.CodeDom;
using System.Diagnostics;
using System.Linq;
using System.Reflection;
using Xml.Schema.Linq.CodeGen.Model;
using Xml.Schema.Linq.Extensions;
using XObjects;

namespace Xml.Schema.Linq.CodeGen
{
    public class CodeDomTypesGenerator
    {
        readonly LinqToXsdSettings settings;
        TypeBuilder typeBuilder;

        // TODO: eventually remove
        XmlQualifiedName rootElementName = XmlQualifiedName.Empty;
        public CodeTypeDeclaration RootElement { get; private set; }
        public IEnumerable<CodeTypeDeclaration> AllRoots => codeNamespacesTable.Values.SelectMany(ns => ns.Roots);

        CNamespace cNamespace, rootNamespace;
        public CNamespace RootNamespace => rootNamespace;

        readonly Dictionary<string, CNamespace> codeNamespacesTable = new();
        Dictionary<XmlSchemaObject, string> nameMappings;
        readonly List<ClrWrapperTypeInfo> wrapperRootElements = [];

        string currentNamespace;
        string currentFullTypeName;

        public readonly List<CType> AllTypes = [];
        // TODO: review naming, this is more an AllTypes than AllElements as it also contains wrapper classes for simple types
        //       but then what's the difference with AllTypes above? is AllElements only the non-nested types? 
        //       I guess I'll figure it out after migrating more code.
        public readonly List<CElement> AllElements = [];
        public readonly List<KeyValuePair<string, string>> AllWrappers = [];

        public CodeDomTypesGenerator(LinqToXsdSettings settings)
        {
            this.settings = settings
                ?? throw new ArgumentNullException(nameof(settings));
        }

        public IEnumerable<CNamespace> GenerateTypes(ClrMappingInfo binding)
        {
            if (binding == null) throw new ArgumentNullException(nameof(binding));

            nameMappings = binding.NameMappings;
            Debug.Assert(nameMappings != null);

            foreach (ClrTypeInfo type in binding.Types)
            {
                if (type.IsWrapper)
                {
                    wrapperRootElements.Add(type as ClrWrapperTypeInfo);
                    continue;
                }
                
                cNamespace = GetCNamespace(type.clrtypeNs);
                Debug.Assert(cNamespace != null);
                var ns = cNamespace.Dom;

                if (type is ClrSimpleTypeInfo stInfo)
                {
                    if (stInfo is EnumSimpleTypeInfo enumTypeInfo)
                    {
                        // The following is already generated in simple type template
                        // var enumType = TypeBuilder.CreateEnumType(enumTypeInfo, settings, stInfo);
                        // cNamespace.Add(enumType); // Enum declaration is generated by simple type template at the same time as validator
                        var enumType = new CodeTypeDeclaration(enumTypeInfo.clrtypeName) { IsEnum = true };

                        // TODO: Figure out how where descendant enum declarations could be generated
                        //       and ensure template doesn't generate them twice.
                        var enumsInOtherTypes = ns.DescendentTypeScopedEnumDeclarations();
                        // if an enum is defined in another type, remove it, if it is the same as the global (namespace scoped type)
                        if (enumsInOtherTypes.EqualEnumDeclarationExists(enumType)) 
                        {
                            var typeWithDuplicateEnum = ns.TypeWithEnumDeclaration(enumType);
                            var duplicateEnum = typeWithDuplicateEnum.Members.OfType<CodeTypeDeclaration>()
                                .First(c => c.IsEqualEnumDeclaration(enumType));
                            typeWithDuplicateEnum.Members.Remove(duplicateEnum);
                        }
                    }

                    cNamespace.Add(new CSimpleType(stInfo, nameMappings, settings));
                }
                else 
                {
                    var decl = ProcessType(type as ClrContentTypeInfo, null, true); // Sets current cNamespace
                    cNamespace.Add(decl);

                    if (type.typeOrigin == SchemaOrigin.Element)
                    {
                        cNamespace.Roots.Add(decl);
                        UpdateRootElement(type, decl);
                    }
                }
            }

            ProcessWrapperTypes();
            CreateXRoots();

            return codeNamespacesTable.Values;
        }

        private CodeTypeDeclaration ProcessType(ClrContentTypeInfo typeInfo, string parentIdentifier, bool globalType)
        {
            SetFullTypeName(typeInfo, parentIdentifier);

            if (globalType)
                currentNamespace = typeInfo.clrtypeNs;

            //Build type using TypeBuilder
            typeBuilder = GetTypeBuilder();
            typeBuilder.CreateTypeDeclaration(typeInfo, cNamespace.Dom);
            ProcessProperties(typeInfo.Content, typeInfo.Annotations);
            typeBuilder.CreateFunctionalConstructor(typeInfo.Annotations);
            typeBuilder.ImplementInterfaces(settings.EnableServiceReference);
            typeBuilder.ApplyAnnotations(typeInfo);

            CodeTypeDeclaration builtType = typeBuilder.TypeDeclaration;
            
            if (globalType)
            {
                // TODO: these shouldn't be a new instances but the instance built above by TypeBuilder, when migrated
                if (typeInfo.typeOrigin == SchemaOrigin.Fragment)
                    AllTypes.Add(new() 
                    { 
                        Name = typeInfo.clrFullTypeName, 
                        XsdName = typeInfo.schemaName, 
                        XsdNs = typeInfo.schemaNs,
                    });
                else
                    AllElements.Add(new() 
                    {
                        Dom = builtType,
                        Name = typeInfo.clrFullTypeName,
                        XsdName = typeInfo.schemaName,
                        XsdNs = typeInfo.schemaNs,
                    });
            }

            ProcessNestedTypes(typeInfo.NestedTypes, builtType, typeInfo.clrFullTypeName);
            return builtType;
        }


        private void ProcessNestedTypes(List<ClrTypeInfo> anonymousTypes, CodeTypeDeclaration parentTypeDecl,
            string parentIdentifier)
        {
            foreach (ClrTypeInfo nestedType in anonymousTypes)
            {
                ClrSimpleTypeInfo stInfo = nestedType as ClrSimpleTypeInfo;
                CodeTypeDeclaration decl = null;
                if (stInfo != null)
                {
                    if (stInfo is EnumSimpleTypeInfo && EnumAlreadyExistsInParent(stInfo.clrtypeName, parentTypeDecl)) continue;

                    decl = TypeBuilder.CreateSimpleType(stInfo, nameMappings, settings);
                    //Anonymous simple types are private within the scope of the parent class
                    decl.TypeAttributes = TypeAttributes.NestedPrivate;
                }
                else
                {
                    decl = ProcessType(nestedType as ClrContentTypeInfo, parentIdentifier, false);
                }

                parentTypeDecl.Members.Add(decl);
                decl.SetParent(parentTypeDecl);
            }
        }

        private void ProcessProperties(IEnumerable<ContentInfo> properties, List<ClrAnnotation> annotations)
        {
            foreach (ContentInfo child in properties)
            {
                //Child can either be a property directly for attributes or a grouping for content model,
                if (child.ContentType == ContentType.Property)
                {
                    ClrPropertyInfo propertyInfo = child as ClrPropertyInfo;
                    Debug.Assert(propertyInfo is not null);
                    propertyInfo.UpdateTypeReference(currentFullTypeName, currentNamespace, nameMappings, CreateNestedEnumType);
                    typeBuilder.CreateAttributeProperty(propertyInfo, null);
                }
                else
                {
                    GroupingInfo rootGroup = child as GroupingInfo;
                    if (rootGroup.IsComplex)
                    {
                        typeBuilder.StartGrouping(rootGroup);
                        ProcessComplexGroupProperties(rootGroup, annotations);
                        typeBuilder.EndGrouping();
                    }
                    else
                    {
                        ProcessGroup(rootGroup, annotations);
                    }
                }
            }
        }

        private void CreateNestedEnumType(ClrTypeReference typeRef)
        {
            if (typeRef == null) throw new ArgumentNullException(nameof(typeRef));
            var parentDecl = typeBuilder.TypeDeclaration;
            if (EnumAlreadyExistsInParent(typeRef.Name, parentDecl))
            {
                //If the enum type is already defined in the parent type, do not create it again
                return;
            }

            var innerType = typeRef.SchemaObject as XmlSchemaSimpleType;
            Debug.Assert(innerType != null);
            var visibilitySetting = this.settings.NamespaceTypesVisibilityMap.ValueForKey(typeRef.Namespace);
            var enumTypeDecl = new CodeTypeDeclaration(typeRef.Name) {
                IsEnum = true,
                TypeAttributes = visibilitySetting.ToTypeAttribute()
            };
            foreach (var facet in innerType.GetEnumFacets()) {
                enumTypeDecl.Members.Add(new CodeMemberField(typeRef.Name, facet.Member));
            }

            enumTypeDecl.UserData[nameof(ClrTypeReference)] = typeRef;

            //Create enum validator type
            var enumTypeInfo = new EnumSimpleTypeInfo(innerType) { clrtypeName = typeRef.Name, clrtypeNs = string.Empty };
            var enumValidatorDecl = TypeBuilder.CreateSimpleType(enumTypeInfo, nameMappings, settings);

            parentDecl.Members.Add(enumTypeDecl);
            parentDecl.Members.Add(enumValidatorDecl);
        }

        private static bool EnumAlreadyExistsInParent(string clrEnumTypeName, CodeTypeDeclaration parent)
        {
            return parent.Members
                .OfType<CodeTypeDeclaration>()
                .Where(m => m.IsEnum)
                .Select(m => m.Name)
                .Contains(clrEnumTypeName);
        }

        private void ProcessGroup(GroupingInfo grouping, List<ClrAnnotation> annotations)
        {
            typeBuilder.StartGrouping(grouping);
            foreach (ContentInfo child in grouping.Children)
            {
                if (child.ContentType == ContentType.Property)
                {
                    ClrPropertyInfo propertyInfo = child as ClrPropertyInfo;
                    propertyInfo.UpdateTypeReference(currentFullTypeName, currentNamespace, nameMappings, CreateNestedEnumType);
                    typeBuilder.CreateProperty(propertyInfo, annotations);
                }
                else if (child.ContentType == ContentType.WildCardProperty)
                {
                    ClrWildCardPropertyInfo propertyInfo = child as ClrWildCardPropertyInfo;
                    typeBuilder.CreateProperty(propertyInfo, annotations);
                }
                else
                {
                    Debug.Assert(child.ContentType == ContentType.Grouping);
                    ProcessGroup(child as GroupingInfo, annotations);
                }
            }

            typeBuilder.EndGrouping();
        }

        private void ProcessComplexGroupProperties(GroupingInfo grouping, List<ClrAnnotation> annotations)
        {
            foreach (ContentInfo child in grouping.Children)
            {
                if (child.ContentType == ContentType.Property)
                {
                    ClrPropertyInfo propertyInfo = child as ClrPropertyInfo;
                    propertyInfo.UpdateTypeReference(currentFullTypeName, currentNamespace, nameMappings, CreateNestedEnumType);
                    typeBuilder.CreateProperty(propertyInfo, annotations);
                }
                else if (child.ContentType == ContentType.WildCardProperty)
                {
                    ClrWildCardPropertyInfo propertyInfo = child as ClrWildCardPropertyInfo;
                    typeBuilder.CreateProperty(propertyInfo, annotations);
                }
                else
                {
                    Debug.Assert(child.ContentType == ContentType.Grouping);
                    typeBuilder.StartGrouping(child as GroupingInfo);
                    ProcessComplexGroupProperties(child as GroupingInfo, annotations);
                    typeBuilder.EndGrouping();
                }
            }
        }

        private void CreateXRoots()
        {
            string rootClrNamespace = settings.GetClrNamespace(rootElementName.Namespace);
            if (!codeNamespacesTable.TryGetValue(rootClrNamespace, out rootNamespace))
            {
                // This might happen if the schema set has no global elements and only global types then you can create a root tag with xsi:type
                rootNamespace = codeNamespacesTable.Values.FirstOrDefault(); 
                // rootCodeNamespace may still be null if schema has only simple typed global elements or simple types which we are ignoring for now
            }
        }

        private void ProcessWrapperTypes()
        {
            if (wrapperRootElements.Count == 0) return;

            var wrapperBuilder = new XWrapperTypedElementBuilder(settings);
            var simpleTypeBuilder = new XSimpleTypedElementBuilder(settings);

            TypeBuilder builder = null;
            ClrPropertyInfo typedValPropertyInfo = null;
            foreach (ClrWrapperTypeInfo typeInfo in wrapperRootElements)
            {
                CClass cType = null;
                SetFullTypeName(typeInfo, null);
                ClrTypeReference innerType = typeInfo.InnerType;
                if (innerType.IsSimpleType)
                {
                    typedValPropertyInfo = InitializeTypedValuePropertyInfo(typeInfo, typedValPropertyInfo, innerType);
                    simpleTypeBuilder.Init(typedValPropertyInfo.ClrTypeName, innerType.IsSchemaList);
                    simpleTypeBuilder.CreateTypeDeclaration(typeInfo, cNamespace.Dom);
                    simpleTypeBuilder.CreateFunctionalConstructor(typeInfo.Annotations);
                    typedValPropertyInfo.SetFixedDefaultValue(typeInfo);
                    simpleTypeBuilder.CreateProperty(typedValPropertyInfo, typeInfo.Annotations);
                    simpleTypeBuilder.ApplyAnnotations(typeInfo);
                    builder = simpleTypeBuilder;

                    // cType = new CSimpleType(typeInfo)
                    // {
                    //   Dom = builder.TypeDeclaration,
                    //   Name = typeInfo.clrtypeName,
                    // };

                    // TODO: should not be a new instance but rather the one produced by code above, when migrated
                    AllElements.Add(new()
                    {
                        Dom = builder.TypeDeclaration,
                        Name = typeInfo.clrFullTypeName,
                        XsdName = typeInfo.schemaName,
                        XsdNs = typeInfo.schemaNs,
                    });
                }
                else
                {
                    string innerTypeName = null;
                    string innerTypeFullName =
                        innerType.GetClrFullTypeName(typeInfo.clrtypeNs, nameMappings, settings, out innerTypeName);
                    string innerTypeNs = innerType.Namespace;

                    CodeNamespace innerTypeCodeNamespace = GetCodeNamespace(innerTypeNs);
                    CodeTypeDeclaration innerTypeDecl = GetCodeTypeDeclaration(innerTypeName, innerTypeCodeNamespace);
                    TypeAttributes innerTypeAttributes = TypeAttributes.Class;
                    if (innerTypeDecl != null)
                    {
                        innerTypeAttributes = innerTypeDecl.TypeAttributes;
                    }
                    else if (innerTypeName != Constants.XTypedElement)
                    {
                        continue;
                    }

                    currentNamespace = typeInfo.clrtypeNs;
                    wrapperBuilder.Init(innerTypeFullName, innerTypeNs, innerTypeAttributes);
                    wrapperBuilder.CreateTypeDeclaration(typeInfo, cNamespace.Dom);
                    wrapperBuilder.CreateFunctionalConstructor(typeInfo.Annotations);
                    wrapperBuilder.ApplyAnnotations(typeInfo);

                    // TODO: shouldn't be a new instance but rather from wrapperBuilder when migrated
                    AllElements.Add(new() 
                    {
                        Dom = wrapperBuilder.TypeDeclaration,
                        Name = typeInfo.clrFullTypeName,
                        XsdName = typeInfo.schemaName,
                        XsdNs = typeInfo.schemaNs,
                    });

                    AllWrappers.Add(new(typeInfo.clrFullTypeName, innerTypeFullName));

                    if (!typeInfo.HasBaseContentType)
                    {
                        //Add innerType properties only if the wrapper's type is not the same as the substitutionGroup head type
                        ClrWrappingPropertyInfo wrappingPropertyInfo = null;
                        //Create forwarding properties
                        if (innerTypeName != Constants.XTypedElement)
                        {
                            //If the wrapped type is xs:anyType, no forwarding properties to create
                            wrappingPropertyInfo = new ClrWrappingPropertyInfo();

                            //Get all properties from the inner type and its base types
                            var memberProperties = innerTypeDecl
                                .GetSelfAndBaseMembers(GetCodeNamespace, GetCodeTypeDeclaration)
                                .OfType<CodeMemberProperty>()
                                .ToArray();

                            foreach (CodeMemberProperty memberProperty in memberProperties)
                            {
                                if (ForwardProperty(memberProperty))
                                {
                                    //Do not forward over TypeManager, SchemaName etc
                                    wrappingPropertyInfo.Init(memberProperty);
                                    wrapperBuilder.CreateProperty(wrappingPropertyInfo, typeInfo.Annotations);
                                }
                            }
                        }
                    }

                    builder = wrapperBuilder;
                }

                builder.ImplementInterfaces(settings.EnableServiceReference);
                var decl = builder.TypeDeclaration;

                cNamespace = GetCNamespace(typeInfo.clrtypeNs);
                if (cType != null)
                    cNamespace.Add(cType);
                else
                    cNamespace.Add(decl);   // TODO: remove at end of migration
                cNamespace.Roots.Add(decl);

                if (typeInfo.typeOrigin == SchemaOrigin.Element) 
                    UpdateRootElement(typeInfo, decl);
            }
        }

        private bool ForwardProperty(CodeMemberProperty property)
        {
            return property != null && property.ImplementationTypes.Count == 0; //Its not an interface impl (IXMetaData)
        }

        private CodeTypeDeclaration GetCodeTypeDeclaration(string typeName, CodeNamespace innerTypeCodeNamespace)
        {
            if (innerTypeCodeNamespace == null)
            {
                return null;
            }

            CodeTypeDeclarationCollection types = innerTypeCodeNamespace.Types;
            foreach (CodeTypeDeclaration decl in types)
            {
                if (decl.Name.Equals(typeName))
                {
                    return decl;
                }
            }

            return null;
        }

        private void AddDefaultImports(CodeNamespace newCodeNamespace)
        {
            newCodeNamespace.Imports.Add(new CodeNamespaceImport("System"));
            newCodeNamespace.Imports.Add(new CodeNamespaceImport("System.Collections"));
            newCodeNamespace.Imports.Add(new CodeNamespaceImport("System.Collections.Generic"));
            newCodeNamespace.Imports.Add(new CodeNamespaceImport("System.ComponentModel"));
            newCodeNamespace.Imports.Add(new CodeNamespaceImport("System.IO"));
            newCodeNamespace.Imports.Add(new CodeNamespaceImport("System.Linq"));
            newCodeNamespace.Imports.Add(new CodeNamespaceImport("System.Diagnostics"));
            newCodeNamespace.Imports.Add(new CodeNamespaceImport("System.Xml"));
            newCodeNamespace.Imports.Add(new CodeNamespaceImport("System.Xml.Schema"));
            if (settings.EnableServiceReference)
            {
                newCodeNamespace.Imports.Add(new CodeNamespaceImport("System.Xml.Serialization"));
            }

            newCodeNamespace.Imports.Add(new CodeNamespaceImport("System.Xml.Linq"));
            newCodeNamespace.Imports.Add(new CodeNamespaceImport("Xml.Schema.Linq"));
        }

        private TypeBuilder GetTypeBuilder()
        {
            if (typeBuilder == null)
                typeBuilder = new XTypedElementBuilder(settings, cNamespace.Dom);
            else
                typeBuilder.Init();

            return typeBuilder;
        }

        private void SetFullTypeName(ClrTypeInfo typeInfo, string parentIdentifier)
        {
            if (parentIdentifier == null)
            {
                if (typeInfo.clrtypeNs == string.Empty)
                    currentFullTypeName = typeInfo.clrtypeName;
                else
                    currentFullTypeName = typeInfo.clrtypeNs + "." + typeInfo.clrtypeName;
            }
            else
            {
                currentFullTypeName = parentIdentifier + "." + typeInfo.clrtypeName;
            }

            typeInfo.clrFullTypeName = currentFullTypeName;
            XmlQualifiedName baseTypeName = typeInfo.BaseTypeName;
            if (baseTypeName != XmlQualifiedName.Empty)
            {
                string clrNamespace = settings.GetClrNamespace(baseTypeName.Namespace);
                if (nameMappings.TryGetValue(typeInfo.baseType, out string baseTypeIdentifier))
                {
                    typeInfo.baseTypeClrName = baseTypeIdentifier;
                    typeInfo.baseTypeClrNs = clrNamespace;
                }
            }

            if (typeInfo.typeOrigin == SchemaOrigin.Element && (rootElementName.IsEmpty || typeInfo.IsRoot))
            {
                rootElementName = new XmlQualifiedName(typeInfo.schemaName, typeInfo.schemaNs);
            }
        }

        private void UpdateRootElement(ClrTypeInfo info, CodeTypeDeclaration decl)
        {
            // The last IsRoot element is assumed to be the schema root element
            // When there is no IsRoot element, then the first element in schema is the assumed root.
            if (info.IsRoot)
                RootElement = decl;
            else
                RootElement ??= decl;
        }

        private ClrPropertyInfo InitializeTypedValuePropertyInfo(ClrTypeInfo typeInfo,
            ClrPropertyInfo existingTypedValPropertyInfo, ClrTypeReference innerType)
        {
            if (existingTypedValPropertyInfo == null)
            {
                existingTypedValPropertyInfo = new ClrPropertyInfo(
                    Constants.SInnerTypePropertyName, 
                    string.Empty,
                    Constants.SInnerTypePropertyName, 
                    Occurs.One, 
                    settings) 
                {                    
                    Origin = SchemaOrigin.Text,
                };
            }
            else
            {
                existingTypedValPropertyInfo.Reset();
            }

            existingTypedValPropertyInfo.TypeReference = innerType;
            if (typeInfo.IsSubstitutionMember())
            {
                existingTypedValPropertyInfo.IsNew = true;
            }

            existingTypedValPropertyInfo.UpdateTypeReference(currentFullTypeName, currentNamespace, nameMappings, CreateNestedEnumType);
            return existingTypedValPropertyInfo;
        }
        
        private CNamespace GetCNamespace(string clrNamespace)
        {
            if (cNamespace?.Name == clrNamespace)
                return cNamespace;

            if (!codeNamespacesTable.TryGetValue(clrNamespace, out CNamespace currentCodeNamespace))
            {
                currentCodeNamespace = new CNamespace(clrNamespace)
                {
                    Dom = new CodeNamespace(clrNamespace),
                    AccessModifier = settings.NamespaceTypesVisibilityMap
                        .GetValueOrDefault(clrNamespace, GeneratedTypesVisibility.Public)
                        .ToKeyword(),
                };
                AddDefaultImports(currentCodeNamespace.Dom);
                codeNamespacesTable.Add(clrNamespace, currentCodeNamespace);
            }

            return currentCodeNamespace;
        }

        private CodeNamespace GetCodeNamespace(string clrNamespace) => GetCNamespace(clrNamespace).Dom;
    }
}