//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Schema;
using Xml.Schema.Linq;



/// <summary>
/// <para>
/// Regular expression: (combos | report | include)*
/// </para>
/// </summary>
public partial class tModular : XTypedElement, IXMetaData {
    
		public static explicit operator tModular(XElement xe) { return XTypedServices.ToXTypedElement<tModular>(xe,LinqToXsdTypeManager.Instance as ILinqToXsdTypeManager); }
    
    public override XTypedElement Clone() {
        return XTypedServices.CloneXTypedElement<tModular>(this);
    }
    
    /// <summary>
    /// <para>
    /// Regular expression: (combos | report | include)*
    /// </para>
    /// </summary>
    public tModular() {
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    protected internal static readonly System.Xml.Linq.XName combosXName = System.Xml.Linq.XName.Get("combos", "");
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private XTypedList<tCombos> combosField;
    
    /// <summary>
    /// <para>
    /// Occurrence: required, choice
    /// </para>
    /// <para>
    /// Regular expression: (combos | report | include)*
    /// </para>
    /// </summary>
    public virtual IList<tCombos> combos {
        get {
            if ((this.combosField == null)) {
                this.combosField = new XTypedList<tCombos>(this, LinqToXsdTypeManager.Instance, combosXName);
            }
            return this.combosField;
        }
        set {
            if ((value == null)) {
                this.combosField = null;
            }
            else {
                if ((this.combosField == null)) {
                    this.combosField = XTypedList<tCombos>.Initialize(this, LinqToXsdTypeManager.Instance, value, combosXName);
                }
                else {
                    XTypedServices.SetList<tCombos>(this.combosField, value);
                }
            }
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    protected internal static readonly System.Xml.Linq.XName reportXName = System.Xml.Linq.XName.Get("report", "");
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private XTypedList<tReport> reportField;
    
    /// <summary>
    /// <para>
    /// Occurrence: required, choice
    /// </para>
    /// <para>
    /// Regular expression: (combos | report | include)*
    /// </para>
    /// </summary>
    public virtual IList<tReport> report {
        get {
            if ((this.reportField == null)) {
                this.reportField = new XTypedList<tReport>(this, LinqToXsdTypeManager.Instance, reportXName);
            }
            return this.reportField;
        }
        set {
            if ((value == null)) {
                this.reportField = null;
            }
            else {
                if ((this.reportField == null)) {
                    this.reportField = XTypedList<tReport>.Initialize(this, LinqToXsdTypeManager.Instance, value, reportXName);
                }
                else {
                    XTypedServices.SetList<tReport>(this.reportField, value);
                }
            }
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    protected internal static readonly System.Xml.Linq.XName includeXName = System.Xml.Linq.XName.Get("include", "");
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private XTypedList<tModular> includeField;
    
    /// <summary>
    /// <para>
    /// Occurrence: required, choice
    /// </para>
    /// <para>
    /// Regular expression: (combos | report | include)*
    /// </para>
    /// </summary>
    public virtual IList<tModular> include {
        get {
            if ((this.includeField == null)) {
                this.includeField = new XTypedList<tModular>(this, LinqToXsdTypeManager.Instance, includeXName);
            }
            return this.includeField;
        }
        set {
            if ((value == null)) {
                this.includeField = null;
            }
            else {
                if ((this.includeField == null)) {
                    this.includeField = XTypedList<tModular>.Initialize(this, LinqToXsdTypeManager.Instance, value, includeXName);
                }
                else {
                    XTypedServices.SetList<tModular>(this.includeField, value);
                }
            }
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    protected internal static readonly System.Xml.Linq.XName @ifXName = System.Xml.Linq.XName.Get("if", "");
    
    /// <summary>
    /// <para>
    /// Occurrence: optional
    /// </para>
    /// </summary>
    public virtual string @if {
        get {
            XAttribute x = this.Attribute(@ifXName);
            if ((x == null)) {
                return null;
            }
            return XTypedServices.ParseValue<string>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
        set {
            this.SetAttribute(@ifXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    protected internal static readonly System.Xml.Linq.XName vXName = System.Xml.Linq.XName.Get("v", "");
    
    /// <summary>
    /// <para>
    /// Occurrence: optional
    /// </para>
    /// </summary>
    public virtual string v {
        get {
            XAttribute x = this.Attribute(vXName);
            if ((x == null)) {
                return null;
            }
            return XTypedServices.ParseValue<string>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
        set {
            this.SetAttribute(vXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    protected internal static readonly System.Xml.Linq.XName labelXName = System.Xml.Linq.XName.Get("label", "");
    
    /// <summary>
    /// <para>
    /// Occurrence: optional
    /// </para>
    /// </summary>
    public virtual string label {
        get {
            XAttribute x = this.Attribute(labelXName);
            if ((x == null)) {
                return null;
            }
            return XTypedServices.ParseValue<string>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
        set {
            this.SetAttribute(labelXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    protected internal static readonly System.Xml.Linq.XName dependsOnXName = System.Xml.Linq.XName.Get("dependsOn", "");
    
    /// <summary>
    /// <para>
    /// Occurrence: optional
    /// </para>
    /// </summary>
    public virtual string dependsOn {
        get {
            XAttribute x = this.Attribute(dependsOnXName);
            if ((x == null)) {
                return null;
            }
            return XTypedServices.ParseValue<string>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
        set {
            this.SetAttribute(dependsOnXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    protected internal static readonly System.Xml.Linq.XName descXName = System.Xml.Linq.XName.Get("desc", "");
    
    /// <summary>
    /// <para>
    /// Occurrence: optional
    /// </para>
    /// </summary>
    public virtual string desc {
        get {
            XAttribute x = this.Attribute(descXName);
            if ((x == null)) {
                return null;
            }
            return XTypedServices.ParseValue<string>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
        set {
            this.SetAttribute(descXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
    }
    
    private static readonly System.Xml.Linq.XName xName = System.Xml.Linq.XName.Get("tModular", "");
    
    static tModular() {
        BuildElementDictionary();
        contentModel = new ChoiceContentModelEntity(new NamedContentModelEntity(combosXName), new NamedContentModelEntity(reportXName), new NamedContentModelEntity(includeXName));
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private static Dictionary<System.Xml.Linq.XName, System.Type> localElementDictionary = new Dictionary<System.Xml.Linq.XName, System.Type>();
    
    private static void BuildElementDictionary() {
        localElementDictionary.Add(combosXName, typeof(tCombos));
        localElementDictionary.Add(reportXName, typeof(tReport));
        localElementDictionary.Add(includeXName, typeof(tModular));
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    Dictionary<System.Xml.Linq.XName, System.Type> IXMetaData.LocalElementsDictionary {
        get {
            return localElementDictionary;
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private static ContentModelEntity contentModel;
    
    ContentModelEntity IXMetaData.GetContentModel() {
        return contentModel;
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    System.Xml.Linq.XName IXMetaData.SchemaName {
        get {
            return xName;
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    SchemaOrigin IXMetaData.TypeOrigin {
        get {
            return SchemaOrigin.Fragment;
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    ILinqToXsdTypeManager IXMetaData.TypeManager {
        get {
            return LinqToXsdTypeManager.Instance;
        }
    }
}

public partial class tReport : XTypedElement, IXMetaData {
    
		public static explicit operator tReport(XElement xe) { return XTypedServices.ToXTypedElement<tReport>(xe,LinqToXsdTypeManager.Instance as ILinqToXsdTypeManager); }
    
    public override XTypedElement Clone() {
        return XTypedServices.CloneXTypedElement<tReport>(this);
    }
    
    public tReport() {
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    protected internal static readonly System.Xml.Linq.XName versionXName = System.Xml.Linq.XName.Get("version", "");
    
    /// <summary>
    /// <para>
    /// Occurrence: optional
    /// </para>
    /// </summary>
    public virtual string version {
        get {
            XAttribute x = this.Attribute(versionXName);
            if ((x == null)) {
                return null;
            }
            return XTypedServices.ParseValue<string>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
        set {
            this.SetAttribute(versionXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
    }
    
    private static readonly System.Xml.Linq.XName xName = System.Xml.Linq.XName.Get("tReport", "");
    
    ContentModelEntity IXMetaData.GetContentModel() {
        return ContentModelEntity.Default;
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    System.Xml.Linq.XName IXMetaData.SchemaName {
        get {
            return xName;
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    SchemaOrigin IXMetaData.TypeOrigin {
        get {
            return SchemaOrigin.Fragment;
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    ILinqToXsdTypeManager IXMetaData.TypeManager {
        get {
            return LinqToXsdTypeManager.Instance;
        }
    }
}

/// <summary>
/// <para>
/// Regular expression: (combo)+
/// </para>
/// </summary>
public partial class tCombos : XTypedElement, IXMetaData {
    
		public static explicit operator tCombos(XElement xe) { return XTypedServices.ToXTypedElement<tCombos>(xe,LinqToXsdTypeManager.Instance as ILinqToXsdTypeManager); }
    
    public override XTypedElement Clone() {
        return XTypedServices.CloneXTypedElement<tCombos>(this);
    }
    
    /// <summary>
    /// <para>
    /// Regular expression: (combo)+
    /// </para>
    /// </summary>
    public tCombos() {
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    protected internal static readonly System.Xml.Linq.XName comboXName = System.Xml.Linq.XName.Get("combo", "");
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private XTypedList<tCombo> comboField;
    
    /// <summary>
    /// <para>
    /// Occurrence: required
    /// </para>
    /// <para>
    /// Regular expression: (combo)+
    /// </para>
    /// </summary>
    public virtual IList<tCombo> combo {
        get {
            if ((this.comboField == null)) {
                this.comboField = new XTypedList<tCombo>(this, LinqToXsdTypeManager.Instance, comboXName);
            }
            return this.comboField;
        }
        set {
            if ((value == null)) {
                this.comboField = null;
            }
            else {
                if ((this.comboField == null)) {
                    this.comboField = XTypedList<tCombo>.Initialize(this, LinqToXsdTypeManager.Instance, value, comboXName);
                }
                else {
                    XTypedServices.SetList<tCombo>(this.comboField, value);
                }
            }
        }
    }
    
    private static readonly System.Xml.Linq.XName xName = System.Xml.Linq.XName.Get("tCombos", "");
    
    static tCombos() {
        BuildElementDictionary();
        contentModel = new SequenceContentModelEntity(new NamedContentModelEntity(comboXName));
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private static Dictionary<System.Xml.Linq.XName, System.Type> localElementDictionary = new Dictionary<System.Xml.Linq.XName, System.Type>();
    
    private static void BuildElementDictionary() {
        localElementDictionary.Add(comboXName, typeof(tCombo));
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    Dictionary<System.Xml.Linq.XName, System.Type> IXMetaData.LocalElementsDictionary {
        get {
            return localElementDictionary;
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private static ContentModelEntity contentModel;
    
    ContentModelEntity IXMetaData.GetContentModel() {
        return contentModel;
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    System.Xml.Linq.XName IXMetaData.SchemaName {
        get {
            return xName;
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    SchemaOrigin IXMetaData.TypeOrigin {
        get {
            return SchemaOrigin.Fragment;
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    ILinqToXsdTypeManager IXMetaData.TypeManager {
        get {
            return LinqToXsdTypeManager.Instance;
        }
    }
}

public partial class tCombo : XTypedElement, IXMetaData {
    
		public static explicit operator tCombo(XElement xe) { return XTypedServices.ToXTypedElement<tCombo>(xe,LinqToXsdTypeManager.Instance as ILinqToXsdTypeManager); }
    
    public override XTypedElement Clone() {
        return XTypedServices.CloneXTypedElement<tCombo>(this);
    }
    
    public tCombo() {
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    protected internal static readonly System.Xml.Linq.XName idXName = System.Xml.Linq.XName.Get("id", "");
    
    /// <summary>
    /// <para>
    /// Occurrence: optional
    /// </para>
    /// </summary>
    public virtual string id {
        get {
            XAttribute x = this.Attribute(idXName);
            if ((x == null)) {
                return null;
            }
            return XTypedServices.ParseValue<string>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Id).Datatype);
        }
        set {
            this.SetAttribute(idXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Id).Datatype);
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    protected internal static readonly System.Xml.Linq.XName nameXName = System.Xml.Linq.XName.Get("name", "");
    
    /// <summary>
    /// <para>
    /// Occurrence: optional
    /// </para>
    /// </summary>
    public virtual string name {
        get {
            XAttribute x = this.Attribute(nameXName);
            if ((x == null)) {
                return null;
            }
            return XTypedServices.ParseValue<string>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
        set {
            this.SetAttribute(nameXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    protected internal static readonly System.Xml.Linq.XName contentXName = System.Xml.Linq.XName.Get("content", "");
    
    /// <summary>
    /// <para>
    /// Occurrence: optional
    /// </para>
    /// </summary>
    public virtual string content {
        get {
            XAttribute x = this.Attribute(contentXName);
            if ((x == null)) {
                return null;
            }
            return XTypedServices.ParseValue<string>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
        set {
            this.SetAttribute(contentXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    protected internal static readonly System.Xml.Linq.XName descXName = System.Xml.Linq.XName.Get("desc", "");
    
    /// <summary>
    /// <para>
    /// Occurrence: optional
    /// </para>
    /// </summary>
    public virtual string desc {
        get {
            XAttribute x = this.Attribute(descXName);
            if ((x == null)) {
                return null;
            }
            return XTypedServices.ParseValue<string>(x, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
        set {
            this.SetAttribute(descXName, value, XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String).Datatype);
        }
    }
    
    private static readonly System.Xml.Linq.XName xName = System.Xml.Linq.XName.Get("tCombo", "");
    
    ContentModelEntity IXMetaData.GetContentModel() {
        return ContentModelEntity.Default;
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    System.Xml.Linq.XName IXMetaData.SchemaName {
        get {
            return xName;
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    SchemaOrigin IXMetaData.TypeOrigin {
        get {
            return SchemaOrigin.Fragment;
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    ILinqToXsdTypeManager IXMetaData.TypeManager {
        get {
            return LinqToXsdTypeManager.Instance;
        }
    }
}

public partial class modular : XTypedElement, IXMetaData {
    
    public void Save(string xmlFile) {
        XTypedServices.Save(xmlFile, Untyped);
    }
    
    public void Save(System.IO.TextWriter tw) {
        XTypedServices.Save(tw, Untyped);
    }
    
    public void Save(System.Xml.XmlWriter xmlWriter) {
        XTypedServices.Save(xmlWriter, Untyped);
    }
    
    public static modular Load(string xmlFile) {
        return XTypedServices.Load<modular, tModular>(xmlFile, LinqToXsdTypeManager.Instance);
    }
    
    public static modular Load(System.IO.TextReader xmlFile) {
        return XTypedServices.Load<modular, tModular>(xmlFile, LinqToXsdTypeManager.Instance);
    }
    
    public static modular Parse(string xml) {
        return XTypedServices.Parse<modular, tModular>(xml, LinqToXsdTypeManager.Instance);
    }
    
		public static explicit operator modular(XElement xe) { return XTypedServices.ToXTypedElement<modular, tModular>(xe,LinqToXsdTypeManager.Instance as ILinqToXsdTypeManager); }
    
    public override XTypedElement Clone() {
        return new modular(((tModular)(this.Content.Clone())));
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private tModular ContentField;
    
    public modular() {
        SetInnerType(new tModular());
    }
    
    public override XElement Untyped {
        get {
            return base.Untyped;
        }
        set {
            base.Untyped = value;
            this.ContentField.Untyped = value;
        }
    }
    
    public virtual tModular Content {
        get {
            return ContentField;
        }
    }
    
    private void SetInnerType(tModular ContentField) {
        this.ContentField = ((tModular)(XTypedServices.GetCloneIfRooted(ContentField)));
        XTypedServices.SetName(this, this.ContentField);
    }
    
    public modular(tModular content) {
        SetInnerType(content);
    }
    
    /// <summary>
    /// <para>
    /// Occurrence: required, choice
    /// </para>
    /// <para>
    /// Regular expression: (combos | report | include)*
    /// </para>
    /// </summary>
    public virtual IList<tCombos> combos {
        get {
            return this.ContentField.combos;
        }
        set {
            this.ContentField.combos = value;
        }
    }
    
    /// <summary>
    /// <para>
    /// Occurrence: required, choice
    /// </para>
    /// <para>
    /// Regular expression: (combos | report | include)*
    /// </para>
    /// </summary>
    public virtual IList<tReport> report {
        get {
            return this.ContentField.report;
        }
        set {
            this.ContentField.report = value;
        }
    }
    
    /// <summary>
    /// <para>
    /// Occurrence: required, choice
    /// </para>
    /// <para>
    /// Regular expression: (combos | report | include)*
    /// </para>
    /// </summary>
    public virtual IList<tModular> include {
        get {
            return this.ContentField.include;
        }
        set {
            this.ContentField.include = value;
        }
    }
    
    /// <summary>
    /// <para>
    /// Occurrence: optional
    /// </para>
    /// </summary>
    public virtual string @if {
        get {
            return this.ContentField.@if;
        }
        set {
            this.ContentField.@if = value;
        }
    }
    
    /// <summary>
    /// <para>
    /// Occurrence: optional
    /// </para>
    /// </summary>
    public virtual string v {
        get {
            return this.ContentField.v;
        }
        set {
            this.ContentField.v = value;
        }
    }
    
    /// <summary>
    /// <para>
    /// Occurrence: optional
    /// </para>
    /// </summary>
    public virtual string label {
        get {
            return this.ContentField.label;
        }
        set {
            this.ContentField.label = value;
        }
    }
    
    /// <summary>
    /// <para>
    /// Occurrence: optional
    /// </para>
    /// </summary>
    public virtual string dependsOn {
        get {
            return this.ContentField.dependsOn;
        }
        set {
            this.ContentField.dependsOn = value;
        }
    }
    
    /// <summary>
    /// <para>
    /// Occurrence: optional
    /// </para>
    /// </summary>
    public virtual string desc {
        get {
            return this.ContentField.desc;
        }
        set {
            this.ContentField.desc = value;
        }
    }
    
    private static readonly System.Xml.Linq.XName xName = System.Xml.Linq.XName.Get("modular", "");
    
    Dictionary<System.Xml.Linq.XName, System.Type> IXMetaData.LocalElementsDictionary {
        get {
            IXMetaData schemaMetaData = ((IXMetaData)(this.Content));
            return schemaMetaData.LocalElementsDictionary;
        }
    }
    
    XTypedElement IXMetaData.Content {
        get {
            return this.Content;
        }
    }
    
    ContentModelEntity IXMetaData.GetContentModel() {
        return ContentModelEntity.Default;
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    System.Xml.Linq.XName IXMetaData.SchemaName {
        get {
            return xName;
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    SchemaOrigin IXMetaData.TypeOrigin {
        get {
            return SchemaOrigin.Element;
        }
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    ILinqToXsdTypeManager IXMetaData.TypeManager {
        get {
            return LinqToXsdTypeManager.Instance;
        }
    }
}

public class LinqToXsdTypeManager : ILinqToXsdTypeManager {
    
    private LinqToXsdTypeManager() {
    }
    
    private static Dictionary<System.Xml.Linq.XName, System.Type> typeDictionary = new Dictionary<System.Xml.Linq.XName, System.Type>();
    
    private static void BuildTypeDictionary() {
        typeDictionary.Add(System.Xml.Linq.XName.Get("tModular", ""), typeof(global::tModular));
        typeDictionary.Add(System.Xml.Linq.XName.Get("tReport", ""), typeof(global::tReport));
        typeDictionary.Add(System.Xml.Linq.XName.Get("tCombos", ""), typeof(global::tCombos));
        typeDictionary.Add(System.Xml.Linq.XName.Get("tCombo", ""), typeof(global::tCombo));
    }
    
    private static Dictionary<System.Xml.Linq.XName, System.Type> elementDictionary = new Dictionary<System.Xml.Linq.XName, System.Type>();
    
    private static void BuildElementDictionary() {
        elementDictionary.Add(System.Xml.Linq.XName.Get("modular", ""), typeof(global::modular));
    }
    
    private static Dictionary<System.Type, System.Type> wrapperDictionary = new Dictionary<System.Type, System.Type>();
    
    private static void BuildWrapperDictionary() {
        wrapperDictionary.Add(typeof(modular), typeof(global::tModular));
    }
    
    private static XmlSchemaSet schemaSet;
    
    XmlSchemaSet ILinqToXsdTypeManager.Schemas {
        get {
            if ((schemaSet == null)) {
                XmlSchemaSet tempSet = new XmlSchemaSet();
                System.Threading.Interlocked.CompareExchange(ref schemaSet, tempSet, null);
            }
            return schemaSet;
        }
        set {
            schemaSet = value;
        }
    }
    
    protected internal static void AddSchemas(XmlSchemaSet schemas) {
        schemas.Add(schemaSet);
    }
    
    Dictionary<System.Xml.Linq.XName, System.Type> ILinqToXsdTypeManager.GlobalTypeDictionary {
        get {
            return typeDictionary;
        }
    }
    
    Dictionary<System.Xml.Linq.XName, System.Type> ILinqToXsdTypeManager.GlobalElementDictionary {
        get {
            return elementDictionary;
        }
    }
    
    Dictionary<System.Type, System.Type> ILinqToXsdTypeManager.RootContentTypeMapping {
        get {
            return wrapperDictionary;
        }
    }
    
    static LinqToXsdTypeManager() {
        BuildTypeDictionary();
        BuildElementDictionary();
        BuildWrapperDictionary();
    }
    
    public static System.Type GetRootType() {
        return elementDictionary[System.Xml.Linq.XName.Get("modular", "")];
    }
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private static LinqToXsdTypeManager typeManagerSingleton = new LinqToXsdTypeManager();
    
    public static LinqToXsdTypeManager Instance {
        get {
            return typeManagerSingleton;
        }
    }
}

public partial class XRootNamespace {
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private XDocument doc;
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private XTypedElement rootObject;
    
    private XRootNamespace() {
    }
    
    public static XRootNamespace Load(string xmlFile) {
        XRootNamespace root = new XRootNamespace();
        root.doc = XDocument.Load(xmlFile);
        XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
        if ((typedRoot == null)) {
            throw new LinqToXsdException("Invalid root element in xml document.");
        }
        root.rootObject = typedRoot;
        return root;
    }
    
    public static XRootNamespace Load(string xmlFile, LoadOptions options) {
        XRootNamespace root = new XRootNamespace();
        root.doc = XDocument.Load(xmlFile, options);
        XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
        if ((typedRoot == null)) {
            throw new LinqToXsdException("Invalid root element in xml document.");
        }
        root.rootObject = typedRoot;
        return root;
    }
    
    public static XRootNamespace Load(TextReader textReader) {
        XRootNamespace root = new XRootNamespace();
        root.doc = XDocument.Load(textReader);
        XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
        if ((typedRoot == null)) {
            throw new LinqToXsdException("Invalid root element in xml document.");
        }
        root.rootObject = typedRoot;
        return root;
    }
    
    public static XRootNamespace Load(TextReader textReader, LoadOptions options) {
        XRootNamespace root = new XRootNamespace();
        root.doc = XDocument.Load(textReader, options);
        XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
        if ((typedRoot == null)) {
            throw new LinqToXsdException("Invalid root element in xml document.");
        }
        root.rootObject = typedRoot;
        return root;
    }
    
    public static XRootNamespace Load(XmlReader xmlReader) {
        XRootNamespace root = new XRootNamespace();
        root.doc = XDocument.Load(xmlReader);
        XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
        if ((typedRoot == null)) {
            throw new LinqToXsdException("Invalid root element in xml document.");
        }
        root.rootObject = typedRoot;
        return root;
    }
    
    public static XRootNamespace Parse(string text) {
        XRootNamespace root = new XRootNamespace();
        root.doc = XDocument.Parse(text);
        XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
        if ((typedRoot == null)) {
            throw new LinqToXsdException("Invalid root element in xml document.");
        }
        root.rootObject = typedRoot;
        return root;
    }
    
    public static XRootNamespace Parse(string text, LoadOptions options) {
        XRootNamespace root = new XRootNamespace();
        root.doc = XDocument.Parse(text, options);
        XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
        if ((typedRoot == null)) {
            throw new LinqToXsdException("Invalid root element in xml document.");
        }
        root.rootObject = typedRoot;
        return root;
    }
    
    public virtual void Save(string fileName) {
        doc.Save(fileName);
    }
    
    public virtual void Save(TextWriter textWriter) {
        doc.Save(textWriter);
    }
    
    public virtual void Save(XmlWriter writer) {
        doc.Save(writer);
    }
    
    public virtual void Save(TextWriter textWriter, SaveOptions options) {
        doc.Save(textWriter, options);
    }
    
    public virtual void Save(string fileName, SaveOptions options) {
        doc.Save(fileName, options);
    }
    
    public virtual XDocument XDocument {
        get {
            return doc;
        }
    }
    
    public virtual XTypedElement Root {
        get {
            return rootObject;
        }
    }
    
    public XRootNamespace(modular root) {
        this.doc = new XDocument(root.Untyped);
        this.rootObject = root;
    }
    

		public modular modular {  get {return rootObject as modular; } }
}

public partial class XRoot {
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private XDocument doc;
    
    [DebuggerBrowsable(DebuggerBrowsableState.Never)]
    private XTypedElement rootObject;
    
    private XRoot() {
    }
    
    public static XRoot Load(string xmlFile) {
        XRoot root = new XRoot();
        root.doc = XDocument.Load(xmlFile);
        XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
        if ((typedRoot == null)) {
            throw new LinqToXsdException("Invalid root element in xml document.");
        }
        root.rootObject = typedRoot;
        return root;
    }
    
    public static XRoot Load(string xmlFile, LoadOptions options) {
        XRoot root = new XRoot();
        root.doc = XDocument.Load(xmlFile, options);
        XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
        if ((typedRoot == null)) {
            throw new LinqToXsdException("Invalid root element in xml document.");
        }
        root.rootObject = typedRoot;
        return root;
    }
    
    public static XRoot Load(TextReader textReader) {
        XRoot root = new XRoot();
        root.doc = XDocument.Load(textReader);
        XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
        if ((typedRoot == null)) {
            throw new LinqToXsdException("Invalid root element in xml document.");
        }
        root.rootObject = typedRoot;
        return root;
    }
    
    public static XRoot Load(TextReader textReader, LoadOptions options) {
        XRoot root = new XRoot();
        root.doc = XDocument.Load(textReader, options);
        XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
        if ((typedRoot == null)) {
            throw new LinqToXsdException("Invalid root element in xml document.");
        }
        root.rootObject = typedRoot;
        return root;
    }
    
    public static XRoot Load(XmlReader xmlReader) {
        XRoot root = new XRoot();
        root.doc = XDocument.Load(xmlReader);
        XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
        if ((typedRoot == null)) {
            throw new LinqToXsdException("Invalid root element in xml document.");
        }
        root.rootObject = typedRoot;
        return root;
    }
    
    public static XRoot Parse(string text) {
        XRoot root = new XRoot();
        root.doc = XDocument.Parse(text);
        XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
        if ((typedRoot == null)) {
            throw new LinqToXsdException("Invalid root element in xml document.");
        }
        root.rootObject = typedRoot;
        return root;
    }
    
    public static XRoot Parse(string text, LoadOptions options) {
        XRoot root = new XRoot();
        root.doc = XDocument.Parse(text, options);
        XTypedElement typedRoot = XTypedServices.ToXTypedElement(root.doc.Root, LinqToXsdTypeManager.Instance);
        if ((typedRoot == null)) {
            throw new LinqToXsdException("Invalid root element in xml document.");
        }
        root.rootObject = typedRoot;
        return root;
    }
    
    public virtual void Save(string fileName) {
        doc.Save(fileName);
    }
    
    public virtual void Save(TextWriter textWriter) {
        doc.Save(textWriter);
    }
    
    public virtual void Save(XmlWriter writer) {
        doc.Save(writer);
    }
    
    public virtual void Save(TextWriter textWriter, SaveOptions options) {
        doc.Save(textWriter, options);
    }
    
    public virtual void Save(string fileName, SaveOptions options) {
        doc.Save(fileName, options);
    }
    
    public virtual XDocument XDocument {
        get {
            return doc;
        }
    }
    
    public virtual XTypedElement Root {
        get {
            return rootObject;
        }
    }
    
    public XRoot(modular root) {
        this.doc = new XDocument(root.Untyped);
        this.rootObject = root;
    }
    

		public modular modular {  get {return rootObject as modular; } }
}
