<?xml version="1.0" encoding="UTF-8"?>
<!--
    Document: $Id: lexsSRwebserviceImpl-abstract-interface.wsdl 1863 2008-12-22 01:23:21Z ys34 $
    LEXS version  : 3.1.4
    Description   : Bindings definitions for Search/Retrieve LEXS Webservice.
-->
<wsdl:definitions 
    targetNamespace="http://usdoj.gov/leisp/lexs/searchretrieve/3.1/ws" 
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:tns="http://usdoj.gov/leisp/lexs/searchretrieve/3.1/ws" 
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns="http://schemas.xmlsoap.org/wsdl/">
        
    <wsdl:import 
        namespace="http://usdoj.gov/leisp/lexs/searchretrieve/3.1/ws" 
        location="lexsSRwebserviceIntf-abstract-interface.wsdl"/>
    
    <wsdl:service name="SRWebService">
        <wsdl:port name="SRWebServiceBean" binding="tns:SRWebServiceSoapBinding">
            <soap:address location="http://localhost:9080/SRWebService/services/SRWebServiceBean"/>
        </wsdl:port>
    </wsdl:service>
    
</wsdl:definitions>
